---
- name: bootstrap k8s cluster
  hosts: cluster
  gather_facts: true
  become: true
  any_errors_fatal: true
  roles:
    - { role: os_base }
    - { role: os_power }
    - { role: k8s_cluster }
    - { role: k8s_flux }
    - { role: k8s_longhorn }
