apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager
      version: v1.19.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    global:
      rbac:
        disableHTTPChallengesRole: true
    crds:
      enabled: true
