apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns-system
spec:
  interval: 1m
  chart:
    spec:
      chart: external-dns
      version: 1.20.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    policy: sync
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/crutonjohn/external-dns-opnsense-webhook
          tag: main@sha256:e2dcc9c9bddb528f320c155574b8f7f6e353225fc82c448eb5246b0de080f1f4
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        env:
          - name: OPNSENSE_API_SECRET
            valueFrom:
              secretKeyRef:
                name: external-dns-secrets
                key: opnsense-secret
          - name: OPNSENSE_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-secrets
                key: opnsense-key
          - name: OPNSENSE_HOST
            value: http://192.168.1.1/
          - name: LOG_LEVEL
            value: debug
    registry: noop
    managedRecordTypes:
      - A
      - AAAA
