apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: reloader
      version: 2.1.5
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  values:
    reloader:
      reloadOnCreate: true
      syncAfterRestart: true
      reloadStrategy: annotations
