apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg-system
spec:
  interval: 1m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
        sidecarLabel: ""
        labels:
          grafana_dashboard: "1"
          grafana_dashboard_folder: cloudnative-pg