apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kyverno
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    grafana:
      enabled: true
      annotations:
        grafana_dashboard_folder: kyverno
    # TODO once a third worker is available again
    # https://kyverno.io/docs/installation/methods/#high-availability-installation
    admissionController:
      # replicas: 3
      serviceMonitor: &service-monitor-config
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    backgroundController:
      # replicas: 2
      serviceMonitor: *service-monitor-config
    cleanupController:
      # replicas: 2
      serviceMonitor: *service-monitor-config
    reportsController:
      # replicas: 2
      serviceMonitor: *service-monitor-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:deployment-mutation
  namespace: kyverno-system
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - patch
      - update
