apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microsocks
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/httptoolkit/docker-socks-tunnel
              tag: v1.2.1@sha256:5ccd90fb41103cffcda301666028c8d85a7bf5c49657aa934235c4b383267626
            args: ["-u", "$(SOCKS_USERNAME)", "-P", "$(SOCKS_PASSWORD)"]
            envFrom:
              - secret: microsocks-secrets
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          metallb.io/allow-shared-ip: default
          metallb.io/address-pool: default-vip
        ports:
          socks5:
            port: 1080
            protocol: TCP
