apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: microsocks
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/httptoolkit/docker-socks-tunnel
              tag: v1.2.0@sha256:4cdb450ac3ad3abadd5393d762ac9ca45192f15c53dbaa0ab10f789478a015e4
            args: ["-u", "$(SOCKS_USERNAME)", "-P", "$(SOCKS_PASSWORD)"]
            envFrom:
              - secret: microsocks-secrets
    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          metallb.io/allow-shared-ip: default
        ports:
          socks5:
            port: 1080
            protocol: TCP
