apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
  namespace: renovate-system
spec:
  interval: 1m
  chart:
    spec:
      chart: renovate
      version: 46.3.6
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: flux-system
  values:
    cronjob:
      schedule: "51 0/6 * * *"
      annotations:
        healthcheckSecret: renovate-config
    renovate:
      existingConfigFile: /config/config.json
    extraVolumes:
      - name: &volume-name renovate-config
        secret:
          secretName: renovate-config
    extraVolumeMounts:
      - name: *volume-name
        mountPath: /config
    envList:
      - name: LOG_LEVEL
        value: debug
      - name: RENOVATE_TOKEN
        valueFrom:
          secretKeyRef:
            name: renovate-github-token
            key: RENOVATE_TOKEN
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-github-token-refresher
  namespace: renovate-system
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/45 * * * *"
          concurrencyPolicy: Replace
        serviceAccount:
          identifier: renovate-github-token-refresher
        annotations:
          healthcheckSecret: renovate-github-token-secrets
        containers:
          main:
            image:
              repository: ghcr.io/anokfireball/base-image
              tag: 3.23.3@sha256:c02a5a9efbc6ef04b1800d0a33d9a5866f69f4912689788e721e3e10b079b96f
            envFrom:
              - secret: renovate-github-token-secrets
            command: ["/bin/bash", "/scripts/token.sh"]
            args: ["$(CLIENT_ID)", "/key/private-key.pem", "$(INSTALLATION_ID)"]
            securityContext:
              runAsUser: 65534
              runAsGroup: 65534
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    serviceAccount:
      renovate-github-token-refresher:
        enabled: true
    rbac:
      roles:
        config-patcher:
          enabled: true
          type: Role
          rules:
            - apiGroups: [""]
              resources: ["secrets"]
              resourceNames: ["renovate-github-token"]
              verbs: ["get", "create", "patch"]
      bindings:
        renovate-github-token-refresher:
          enabled: true
          type: RoleBinding
          roleRef:
            name: renovate-github-token-refresher-config-patcher
            kind: Role
          subjects:
            - kind: ServiceAccount
              name: renovate-github-token-refresher
              namespace: renovate-system
    configMaps:
      scripts:
        data:
          # https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app
          token.sh: |
            #!/usr/bin/env bash
            set -o pipefail

            CLIENT_ID=$1
            PEM_PATH=$2
            INSTALLATION_ID=$3


            NOW=$(date +%s)
            IAT=$(($NOW - 60))  # Issues 60 seconds in the past
            EXP=$(($NOW + 300)) # Expires 5 minutes in the future

            b64enc() { openssl base64 | tr -d '=' | tr '/+' '_-' | tr -d '\n'; }

            HEADER_JSON='{
                "typ":"JWT",
                "alg":"RS256"
            }'
            # Header encode
            HEADER=$(echo -n "$HEADER_JSON" | b64enc)

            PAYLOAD_JSON="{
                \"iat\":$IAT,
                \"exp\":$EXP,
                \"iss\":\"$CLIENT_ID\"
            }"
            # Payload encode
            PAYLOAD=$(echo -n "$PAYLOAD_JSON" | b64enc)

            # Signature
            PEM=$(cat "$PEM_PATH")
            HEADER_PAYLOAD="$HEADER"."$PAYLOAD"
            SIGNATURE=$(
                openssl dgst -sha256 -sign <(echo -n "$PEM") \
                <(echo -n "$HEADER_PAYLOAD") | b64enc
            )

            # Create JWT
            JWT="$HEADER_PAYLOAD"."$SIGNATURE"

            TOKEN_JSON=$(curl --request POST \
              --url "https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens" \
              --header "Accept: application/vnd.github+json" \
              --header "Authorization: Bearer $JWT" \
              --header "X-GitHub-Api-Version: 2022-11-28")
            TOKEN=$(echo "$TOKEN_JSON" | jq -r '.token')
            if [ -z "$TOKEN" ]; then
              echo "ERROR: Failed to retrieve token from GitHub API."
              exit 1
            fi

            TOKEN_ENCODED=$(echo -n "$TOKEN" | base64)

            if kubectl get secret renovate-github-token -n renovate-system >/dev/null 2>&1; then
              echo "Secret exists, patching..."
              PATCH=$(printf '[{"op": "replace", "path": "/data/RENOVATE_TOKEN", "value":"%s"}]' "$TOKEN_ENCODED")
              kubectl patch secret renovate-github-token -n renovate-system --type='json' -p="$PATCH" || { echo "Patch failed!"; exit 1; }
            else
              echo "Secret does not exist, creating..."
              kubectl create secret generic renovate-github-token -n renovate-system --from-literal=RENOVATE_TOKEN="$TOKEN_ENCODED" || { echo "Create failed!"; exit 1; }
            fi
    persistence:
      scripts:
        type: configMap
        name: renovate-github-token-refresher-scripts
      key:
        type: secret
        name: renovate-github-token-key
