apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: spegel-system
spec:
  interval: 1m
  chart:
    spec:
      chart: spegel
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: spegel
        namespace: flux-system
  values:
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
    grafanaDashboard:
      enabled: true
      annotations:
        grafana_dashboard_folder: spegel
