apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.86.2
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  values:
    operatorConfig:
      defaultTags:
        - "tag:k8s-operator"
        - "tag:k8s-homelab"
      hostname: "tailscale-operator-homelab"
    proxyConfig:
      defaultTags: "tag:k8s,tag:k8s-homelab"
