apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 1m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.84.2
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
