apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: vpa
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  dependsOn:
    - name: metrics-server
      namespace: kube-system
  values:
    # only used for goldilocks right now, so only the recommender is needed
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.4.1@sha256:40b6d76e8526806c4f3bc33e725c015ddd7fa339bedf55986a7bed93947c865d
    updater:
      enabled: false
    admissionController:
      enabled: false
    metrics-server:
      enabled: false
