apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: vpa
      version: 4.10.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  dependsOn:
    - name: metrics-server
      namespace: kube-system
  values:
    # only used for goldilocks right now, so only the recommender is needed
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.6.0@sha256:4af365370c187e4eb60302e937b18a188774698b049a1bfdd77d43e51b30abec
    updater:
      enabled: false
    admissionController:
      enabled: false
    metrics-server:
      enabled: false
