apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: kube-system
spec:
  interval: 1m
  chart:
    spec:
      chart: vpa
      version: 4.8.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  dependsOn:
    - name: metrics-server
      namespace: kube-system
  values:
    # only used for goldilocks right now, so only the recommender is needed
    recommender:
      enabled: true
      image:
        repository: registry.k8s.io/autoscaling/vpa-recommender
        tag: 1.4.2@sha256:5ab71cfcd56c480db16af77accb9defdc70442d83cabcfea6e3d4d0243837328
    updater:
      enabled: false
    admissionController:
      enabled: false
    metrics-server:
      enabled: false
