apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/hotio/prowlarr
              tag: release@sha256:06bb8c131cba5823f178fb919ce0152b9ad3b516c2298119e6f6e805844df8c4
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 9696
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: prowlarr.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: prowlarr-tls
            hosts:
              - prowlarr.${SERVICE_DOMAIN}
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/hotio/radarr
              tag: release@sha256:769450abd3fed087fd1381d138af77513f72fc753e0f5c9aba5e5dbd87410f7b
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 7878
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: radarr.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: radarr-tls
            hosts:
              - radarr.${SERVICE_DOMAIN}
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/hotio/sonarr
              tag: release@sha256:d9e0c94c3377714dbe4740c6c4a4e0b8285956b0ae3419ba0ee066d13f76dff0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 8989
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: sonarr.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: sonarr-tls
            hosts:
              - sonarr.${SERVICE_DOMAIN}
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/hotio/lidarr
              tag: release@sha256:53f81223368e4954a37ef01e36c667a90fed6a7291da2c2b501cabfc8c8835f4
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 8686
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: lidarr.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: lidarr-tls
            hosts:
              - lidarr.${SERVICE_DOMAIN}
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 1Gi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flaresolverr
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.6@sha256:7962759d99d7e125e108e0f5e7f3cdbcd36161776d058d1d9b7153b92ef1af9e
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 8191
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: flaresolverr.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: flaresolverr-tls
            hosts:
              - flaresolverr.${SERVICE_DOMAIN}
