apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: excalidraw
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: excalidraw/excalidraw
              # official images are not verisoned beyond "latest" currently
              tag: latest@sha256:9f32b5b5988fdfc0134fc32124f2e60bb472445a14db9d73bfc19108f06ddabe
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: excalidraw.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: excalidraw-tls
            hosts:
              - excalidraw.${SERVICE_DOMAIN}
