apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    enableRbac: true
    ingress:
      main:
        enabled: false
    config:
      useExistingConfigMap: homepage-config
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.${SERVICE_DOMAIN}"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-ext
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.13.2@sha256:a0b71c8e757298d02560186bab9fbe3fc2d375c523a62cc1019177b37e48aa28
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    enableRbac: true
    service:
      main:
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: homelab-homepage-ext
    config:
      useExistingConfigMap: homepage-ext-config
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "links.${EXT_DOMAIN_1},links.${EXT_DOMAIN_2},localhost:3000"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage-gateway
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: homepage
    hostname: homepage.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: homepage
        port: 3000
