apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: homepage
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.4.3@sha256:ce3389bbd09d6e144088891c8abf532f6fe0b7b70a601ca87053d559d2933f75
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    enableRbac: true
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: homepage.${SERVICE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: homepage-tls
            hosts:
              - homepage.${SERVICE_DOMAIN}
    config:
      useExistingConfigMap: homepage-config
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "homepage.${SERVICE_DOMAIN}"
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
