apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: 10.11.7@sha256:2b93aa3830dcd0aab7185c635e20edef1f8dc5d2e999768baf1724e88c078004
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      parentRefs:
        - group: gateway.networking.x-k8s.io
          kind: XListenerSet
          name: jellyfin
          namespace: arrchive
          sectionName: https
      hostnames:
        - jellyfin.${SERVICE_DOMAIN}
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
    volumes:
      - name: nas-filme
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Filme
      - name: nas-serien
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Serien
      # - name: gpu
      #   hostPath:
      #     path: /dev/dri/renderD128
    volumeMounts:
      - name: nas-filme
        mountPath: /mnt/tank/Filme
      - name: nas-serien
        mountPath: /mnt/tank/Serien
      # - name: gpu
      #   mountPath: /dev/dri/renderD128
    # podSecurityContext:
    #   # 'render' on the hosts
    #   fsGroup: 993
    # securityContext:
    #   # need access to the GPU
    #   privileged: true
    persistence:
      config:
        storageClass: cluster-replicated
        size: 10Gi
      media:
        enabled: false
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: envoy-gateway-system
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.${SERVICE_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: jellyfin
  namespace: arrchive
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: jellyfin.${SERVICE_DOMAIN}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: jellyfin-tls
            namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin-http-redirect
  namespace: arrchive
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - jellyfin.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
