apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: 10.11.4@sha256:37f2625f5d5d70c5b1ceb57f4d8f2a7ff666ea723fb96b468275bbafbde2c06c
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: jellyfin.${SERVICE_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: jellyfin-tls
          hosts:
            - jellyfin.${SERVICE_DOMAIN}
    volumes:
      - name: nas-filme
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Filme
      - name: nas-serien
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Serien
      # - name: gpu
      #   hostPath:
      #     path: /dev/dri/renderD128
    volumeMounts:
      - name: nas-filme
        mountPath: /mnt/tank/Filme
      - name: nas-serien
        mountPath: /mnt/tank/Serien
      # - name: gpu
      #   mountPath: /dev/dri/renderD128
    # podSecurityContext:
    #   # 'render' on the hosts
    #   fsGroup: 993
    # securityContext:
    #   # need access to the GPU
    #   privileged: true
    persistence:
      config:
        storageClass: cluster-replicated
        size: 10Gi
      media:
        enabled: false
