apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: jellyfin
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: jellyfin
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/jellyfin/jellyfin
      tag: 10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
    ingress:
      enabled: false
    httpRoute:
      enabled: true
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: ListenerSet
          name: jellyfin
          namespace: arrchive
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
    volumes:
      - name: nas-filme
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Filme
      - name: nas-serien
        nfs:
          server: 192.168.1.2
          path: /mnt/tank/Serien
      # - name: gpu
      #   hostPath:
      #     path: /dev/dri/renderD128
    volumeMounts:
      - name: nas-filme
        mountPath: /mnt/tank/Filme
      - name: nas-serien
        mountPath: /mnt/tank/Serien
      # - name: gpu
      #   mountPath: /dev/dri/renderD128
    # podSecurityContext:
    #   # 'render' on the hosts
    #   fsGroup: 993
    # securityContext:
    #   # need access to the GPU
    #   privileged: true
    persistence:
      config:
        storageClass: cluster-replicated
        size: 10Gi
      media:
        enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin-gateway
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: jellyfin
    hostname: jellyfin.${SERVICE_DOMAIN}
