apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - arr-stack.yaml
  - bitwarden.yaml
  - excalidraw.yaml
  - firefly.yaml
  - fresh-rss.yaml
  - homepage
  - immich.yaml
  - jellyfin.yaml
  - kitchenowl.yaml
  - n8n.yaml
  - nextcloud.yaml
  - opnsense-ipv6-prefix-update.yaml
  - paperless.yaml
  - pihole.yaml
  - qbittorrent.yaml
  - rss-bridge.yaml
  - sabnzbd.yaml
  - soundcloud-scraper.yaml
  - stirling-pdf.yaml
  - unifi.yaml
