apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opnsense-ipv6-prefix-update
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.1.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/1 * * * *"
        annotations:
          healthcheckSecret: opnsense-ipv6-prefix-update-secrets
        containers:
          main:
            image:
              repository: ghcr.io/anokfireball/opnsense-ipv6-prefix-update
              tag: v1.0.3@sha256:5371e931a8e186f914e2261ec4832b220f95e478986bb1365157026490fba00a
            env:
              OPNSENSE_HOST: 192.168.1.1
              OPNSENSE_PORT: 80
              OPNSENSE_SSL: "false"
              OPNSENSE_VERIFY_SSL: "true"
              IPV6_PREFIX_LENGTH: 57
            envFrom:
              - secret: opnsense-ipv6-prefix-update-secrets
