apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opnsense-ipv6-prefix-update
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/1 * * * *"
        annotations:
          healthcheckSecret: opnsense-ipv6-prefix-update-secrets
          healthcheckImage: ghcr.io/anokfireball/base-image:3.24.1@sha256:5ba1b45209afa71ea265b0f02ab4bbb0265f177af51e66b1a4c4fd98e22ca504
        containers:
          main:
            image:
              repository: ghcr.io/anokfireball/opnsense-ipv6-prefix-update
              tag: v1.0.5@sha256:0b5332e60d856a47203bd28ee3df1143446c23c33c831ddf3b8fa8c4b5d92103
            env:
              OPNSENSE_HOST: 192.168.1.1
              OPNSENSE_PORT: 80
              OPNSENSE_SSL: "false"
              OPNSENSE_VERIFY_SSL: "true"
              IPV6_PREFIX_LENGTH: 57
            envFrom:
              - secret: opnsense-ipv6-prefix-update-secrets
