apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    global:
      alwaysAppendIdentifierToResourceName: true
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          permissions:
            image:
              repository: ghcr.io/anokfireball/base-image
              tag: 3.22.2@sha256:13b9d527462d22397ca99396a20224ded04dacf964d463e6d90e4722fc1e3201
            command: ["chown"]
            args: ["1000:1000", "/incomplete-downloads"]
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/qbittorrent
              tag: 5.1.2@sha256:51dd497bd9b1de06fc1f9c9753297fae1e7445ad817e4528ee3f84c9c3122c7d
            env:
              - name: PUID
                value: 1000
              - name: PGID
                value: 1000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - bash
                      - /healthcheck/check-dht.sh
                  periodSeconds: 60
                  timeoutSeconds: 2
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    port: 8080
                  periodSeconds: 5
                  timeoutSeconds: 5
                  failureThreshold: 60
            resources:
              requests:
                cpu: 400m
                memory: 400Mi
          gluetun:
            dependsOn: main
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.40.0@sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00
            env:
              HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH: /config-auth
            envFrom:
              - secret: gluetun-secrets
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
            probes:
              liveness: &gluetun-probe
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /gluetun-entrypoint
                      - healthcheck
                  periodSeconds: 60
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *gluetun-probe
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
          port-forward:
            dependsOn: gluetun
            image:
              repository: snoringdragon/gluetun-qbittorrent-port-manager
              tag: 1.3@sha256:679b7a92c494f93b78ad37ef24f3a261e73d0a1a52505ad4f1e39580eedfa14f
            env:
              QBITTORRENT_SERVER: localhost
              QBITTORRENT_PORT: "8080"
              PORT_FORWARDED: "/tmp/gluetun/forwarded_port"
            envFrom:
              - secret: gluetun-secrets
            resources:
              requests:
                cpu: 10m
                memory: 35Mi
          logs:
            image:
              repository: ghcr.io/anokfireball/base-image
              tag: stable@sha256:7edf5efe6b86dbf01ccc3c76b32a37a8e23b84e6bad81ce8ae8c221fa456fda8
            command: ["tail"]
            args: ["-F", "/config/qBittorrent/logs/qbittorrent.log"]
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
      gluetun:
        controller: main
        ports:
          http:
            port: 8000
    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: qbittorrent.${SERVICE_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: qbittorrent-tls
            hosts:
              - qbittorrent.${SERVICE_DOMAIN}
    configMaps:
      healthcheck:
        data:
          check-dht.sh: |
            #!/bin/bash
            status="$(qbt global info)"
            nodes=$(echo "$status" | sed -n 's/.*DHT nodes:\s*\([0-9]\+\).*/\1/p')
            if [ -n "$nodes" ] && [ "$nodes" -gt 0 ]; then
              exit 0
            fi
            exit 1
    persistence:
      healthcheck:
        type: configMap
        name: qbittorrent-healthcheck
      gluetun-auth:
        type: secret
        name: gluetun-auth
        advancedMounts:
          main:
            gluetun:
              - path: /gluetun/auth
      gluetun-data:
        type: emptyDir
        advancedMounts:
          main:
            gluetun:
              - path: /tmp/gluetun
            port-forward:
              - path: /tmp/gluetun
                readOnly: true
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 500Mi
      logs:
        type: emptyDir
        sizeLimit: 500Mi
        globalMounts:
          - path: /config/qBittorrent/logs/
      incomplete-downloads:
        type: persistentVolumeClaim
        storageClass: cluster-scratch
        accessMode: ReadWriteOnce
        size: 100Gi
      downloads:
        type: nfs
        server: 192.168.1.2
        path: /mnt/tank/Scratch/Torrent
