apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/linuxserver/sabnzbd
              tag: 5.0.4@sha256:f12cb77b4e16d2d60fc8226e433daf69884e83874d90447c6ff1d57ef4247d6f
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 400m
                memory: 500Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: false
    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: sabnzbd
            namespace: arrchive
            sectionName: https
        hostnames:
          - sabnzbd.${SERVICE_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 500Mi
      incomplete-downloads:
        type: persistentVolumeClaim
        storageClass: cluster-scratch
        accessMode: ReadWriteOnce
        size: 100Gi
      downloads:
        type: nfs
        server: 192.168.1.2
        path: /mnt/tank/Scratch/NZB
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sabnzbd-gateway
  namespace: arrchive
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: sabnzbd
    hostname: sabnzbd.${SERVICE_DOMAIN}
