apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: soundcloud-scraper
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: cronjob
        cronjob:
          schedule: "*/15 * * * *"
          concurrencyPolicy: Replace
        annotations:
          healthcheckSecret: soundcloud-scraper-secrets
        containers:
          main:
            image:
              repository: ghcr.io/anokfireball/soundcloud-scraper
              tag: v1.3.0@sha256:d6572c8d81195aedc0dbc10df08798f7bd3dc046ec71fd13ace9aa48723103a1
            env:
              DATA_DIR: /data
              SOUNDCLOUD_USERNAME: psykko0
            envFrom:
              - secret: soundcloud-scraper-secrets
    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: cluster-replicated
        accessMode: ReadWriteOnce
        size: 500Mi
