apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: stirling-tools/stirling-pdf
      tag: 1.4.0-fat@sha256:a8d2646bc24a0fd104a6fdad4306218cecebea9bcb1a06fd8dc8b3407050051c
    envs:
      - name: SYSTEM_DEFAULTLOCALE
        value: de-DE
      - name: SYSTEM_SHOWUPDATE
        value: "false"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 1G
      hosts:
      - name: stirling-pdf.${SERVICE_DOMAIN}
        path: /
        tls: true
        tlsSecret: stirling-pdf-tls
    resources:
      requests:
        cpu: 10m
        memory: 600Mi
    probes:
      liveness:
        initialDelaySeconds: 30
      readiness:
        initialDelaySeconds: 30
