apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: stirling-tools/stirling-pdf
      tag: 2.4.0-fat@sha256:425dd4e9a5ec4e39e1f7656bc1e2eba02b0d3cd9de9f074419f1c3a6623d0f5f
    # https://docs.stirlingpdf.com/Configuration/
    envs:
      - name: SYSTEM_DEFAULTLOCALE
        value: de-DE
      - name: SYSTEM_SHOWUPDATE
        value: "false"
      - name: SYSTEM_GOOGLEVISIBILITY
        value: "false"
      - name: SYSTEM_ENABLEANALYTICS
        value: "false"
      - name: METRICS_ENABLED
        value: "false"
      - name: SECURITY_ENABLELOGIN
        value: "false"
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-body-size: 1G
      hosts:
        - name: stirling-pdf.${SERVICE_DOMAIN}
          path: /
          tls: true
          tlsSecret: stirling-pdf-tls
    resources:
      requests:
        cpu: 10m
        memory: 600Mi
    securityContext:
      enabled: false
    deployment:
      extraVolumes:
        - name: fonts-tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
      extraVolumeMounts:
        - name: fonts-tmpfs
          mountPath: /usr/share/fonts/truetype
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 60
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        enabled: true
        initialDelaySeconds: 40
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
