apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: flux-system
  values:
    image:
      registry: ghcr.io
      repository: stirling-tools/stirling-pdf
      tag: 2.14.0-fat@sha256:d44d101a25a5a6e5f4d706bb37788678c0d514332f144ef9c65984d14c078199
    # https://docs.stirlingpdf.com/Configuration/
    envs:
      - name: SYSTEM_DEFAULTLOCALE
        value: de-DE
      - name: SYSTEM_SHOWUPDATE
        value: "false"
      - name: SYSTEM_GOOGLEVISIBILITY
        value: "false"
      - name: SYSTEM_ENABLEANALYTICS
        value: "false"
      - name: METRICS_ENABLED
        value: "false"
      - name: SECURITY_ENABLELOGIN
        value: "false"
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 10m
        memory: 600Mi
    securityContext:
      enabled: false
    deployment:
      extraVolumes:
        - name: fonts-tmpfs
          emptyDir:
            medium: Memory
            sizeLimit: 100Mi
      extraVolumeMounts:
        - name: fonts-tmpfs
          mountPath: /usr/share/fonts/truetype
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stirling-pdf-tls
  namespace: envoy-gateway-system
spec:
  secretName: stirling-pdf-tls
  dnsNames:
    - stirling-pdf.${SERVICE_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: stirling-pdf
  namespace: default
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: stirling-pdf.${SERVICE_DOMAIN}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: stirling-pdf-tls
            namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: stirling-pdf-listenerset-to-stirling-pdf-tls
  namespace: envoy-gateway-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      namespace: default
  to:
    - group: ""
      kind: Secret
      name: stirling-pdf-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stirling-pdf
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: stirling-pdf
      namespace: default
      sectionName: https
  hostnames:
    - stirling-pdf.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: stirling-pdf-stirling-pdf-chart
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stirling-pdf-http-redirect
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - stirling-pdf.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
