apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vert
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 5.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/vert-sh/vert
              tag: main@sha256:ed2afd55ef8207ddf9029b57ac0c1b63e0ab21cf493a56f787a13e1ea2ac056f
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: false
    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: vert
            namespace: default
            sectionName: https
        hostnames:
          - vert.${SERVICE_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vert-gateway
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: vert
    hostname: vert.${SERVICE_DOMAIN}
