apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vert
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/vert-sh/vert
              tag: main@sha256:6492f2a88e977e7ce82fd26f49028a17575fee8cac38604f585bc5773298cbc8
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      main:
        controller: main
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: false
    route:
      main:
        enabled: true
        kind: HTTPRoute
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: vert
            namespace: default
            sectionName: https
        hostnames:
          - vert.${SERVICE_DOMAIN}
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            backendRefs:
              - identifier: main
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vert-tls
  namespace: envoy-gateway-system
spec:
  secretName: vert-tls
  dnsNames:
    - vert.${SERVICE_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: vert
  namespace: default
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: vert.${SERVICE_DOMAIN}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: vert-tls
            namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: vert-listenerset-to-vert-tls
  namespace: envoy-gateway-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      namespace: default
  to:
    - group: ""
      kind: Secret
      name: vert-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vert-http-redirect
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - vert.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
