apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wger-postgresql
  namespace: default
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.10-29@sha256:802bf1479ef7b0e0655749203cded4ecbc9a114841273de71cb205f3a03254cd
  instances: 1
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: backup
        passwordSecret:
          name: postgres-backup-user
        login: true
        superuser: false
        inRoles:
          - pg_read_all_data
  bootstrap:
    initdb:
      database: wger
      owner: wger
      secret:
        name: wger-postgres-user
  storage:
    size: 2Gi
    storageClass: cluster-replicated
---
apiVersion: k8up.io/v1
kind: PreBackupPod
metadata:
  name: wger-database-backup
  namespace: default
  labels:
    backup: wger-database
  annotations:
    k8up.io/backup: "true"
spec:
  backupCommand: sh -c 'PGHOST="$POSTGRES_HOST" PGUSER="$POSTGRES_USER" PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall --clean'
  pod:
    spec:
      containers:
        - name: wger-database-backup
          image: postgres:15.12-alpine@sha256:ef4879231c4a490f8365bef5dfa2c137d95b7d7703d0b53605693091be48d5b4
          command:
            - "sleep"
            - "infinity"
          env:
            - name: POSTGRES_HOST
              value: wger-postgresql-rw
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-user
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-backup-user
                  key: password
---
apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: wger-database
  namespace: default
spec:
  backend:
    repoPasswordSecretRef:
      name: k8up-restic-secrets
      key: restic-password
    s3:
      bucket: Habitat-Giggle9-Composer/wger
  backup:
    labelSelectors:
      - matchLabels:
          backup: wger-database
    schedule: "42 3/6 * * *"
    concurrentRunsAllowed: false
  prune:
    schedule: "12 0 1 * *"
    concurrentRunsAllowed: false
    retention:
      keepHourly: 6
      keepDaily: 14
      keepWeekly: 12
      keepMonthly: 6
      keepYearly: 2
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wger
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: wger
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: wger
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: wger-secrets
      valuesKey: SECRET_KEY
      targetPath: app.django.secret.key
    - kind: Secret
      name: wger-secrets
      valuesKey: SIGNING_KEY
      targetPath: app.jwt.secret.key
  values:
    app:
      timezone: "Europe/Berlin"
      nginx:
        enabled: true
      persistence:
        enabled: true
        storageClass: nas-replicated-hdd
        accessModes:
          - ReadWriteMany
        sizeMedia: 2Gi
        sizeStatic: 1Gi
        sizeCeleryBeat: 1Gi
      django:
        existingDatabase:
          enabled: true
          engine: django.db.backends.postgresql
          host: wger-postgresql-rw
          port: 5432
          existingSecret:
            name: wger-postgres-user
            dbuserKey: username
            dbpwKey: password
          dbname: wger
      environment:
        - name: GUNICORN_CMD_ARGS
          value: "--workers 2 --threads 2 --worker-class gthread --timeout 240"
        - name: ALLOW_REGISTRATION
          value: "True"
        - name: EXPOSE_PROMETHEUS_METRICS
          value: "True"
        - name: DJANGO_CACHE_CLIENT_CLASS
          value: "django_redis.client.DefaultClient"
        - name: SITE_URL
          value: "https://wger.${SERVICE_DOMAIN}"
    celery:
      enabled: true
    ingress:
      enabled: false
    service:
      port: 8000
    postgres:
      enabled: false
    redis:
      enabled: true
      auth:
        enabled: false
      storage:
        requestedSize: 2Gi
        className: cluster-scratch
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wger-tls
  namespace: envoy-gateway-system
spec:
  secretName: wger-tls
  dnsNames:
    - wger.${SERVICE_DOMAIN}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: wger
  namespace: default
spec:
  parentRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: wger.${SERVICE_DOMAIN}
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: wger-tls
            namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: wger-listenerset-to-wger-tls
  namespace: envoy-gateway-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      namespace: default
  to:
    - group: ""
      kind: Secret
      name: wger-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wger
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: wger
      namespace: default
      sectionName: https
  hostnames:
    - wger.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: wger-http
          port: 8000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: wger-http-redirect
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - wger.${SERVICE_DOMAIN}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
