apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-snapshotter
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/longhorn/csi-snapshotter.git
  ref:
    tag: v8.2.0
