apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: envoy-gateway-upstream
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/envoyproxy/gateway.git
  ref:
    tag: v1.7.2
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  type: oci
  url: oci://docker.io/envoyproxy
