apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8up
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/k8up-io/k8up.git
  ref:
    tag: k8up-4.8.6
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up-io
  namespace: flux-system
spec:
  url: https://k8up-io.github.io/k8up
