---
- when: inventory_hostname == "controlplane1"
  block:
    - name: download flux checksums
      get_url:
        url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_checksums.txt"
        dest: /tmp/flux_{{ flux_version }}_checksums.txt

    - name: extract flux binary checksum
      command: grep "flux_{{ flux_version }}_linux_amd64.tar.gz" /tmp/flux_{{ flux_version }}_checksums.txt
      changed_when: false
      register: flux_checksum
      failed_when: flux_checksum.stdout == ""

    - name: download flux archive
      get_url:
        url: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
        dest: /tmp/flux_{{ flux_version }}_linux_amd64.tar.gz
        checksum: "sha256:{{ flux_checksum.stdout.split()[0] }}"

    - name: extract flux binary
      unarchive:
        src: /tmp/flux_{{ flux_version }}_linux_amd64.tar.gz
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: "0755"
        remote_src: true

    - name: obtain secrets
      community.sops.load_vars:
        file: secrets.sops.yaml

    - name: create sops age key secret manifest
      template:
        src: sops-age.secret.yaml.j2
        dest: /tmp/sops-age.secret.yaml
        owner: root
        group: root
        mode: "0640"
      changed_when: false

    - name: apply sops age key secret
      command: kubectl apply -f /tmp/sops-age.secret.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: sops_age_secret
      changed_when: '" created" in sops_age_secret.stdout or " configured" in sops_age_secret.stdout'

    - name: clean up age key secret manifest
      file:
        path: /tmp/sops-age.secret.yaml
        state: absent
      changed_when: false

    - name: bootstrap flux
      command: >
        flux bootstrap github
          --token-auth
          --owner={{ github_user }}
          --repository={{ github_repository }}
          --branch={{ github_branch }}
          --path=flux/clusters/homelab
          --personal
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
        GITHUB_TOKEN: "{{ github_personal_access_token }}"
      register: flux_bootstrap
      changed_when: false
      failed_when: flux_bootstrap.rc != 0

    - name: flux sanity check
      command: flux check
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: flux_check
      changed_when: false
      failed_when: flux_check.rc != 0
