apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:4fUxcOPZ6IVyIYP7JqjjJVyLvc8w0S1cWSF9elSM51upu5Rm2loK6tw=,iv:c+apypxhYctEdIM99PKu12JE/O/24FGKwwz+ecmFbdw=,tag:0ZXE6mEwWUX9QKDN2jR9Aw==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:osJUak4PvDBNl7ukSQeyN4z7360yATyCfS8RigACJKBeQAEk3hEzm+sk2Bm/Q/p/Hk6zNzNwZOSJ3tjYQjO/hA==,iv:cNbOuMUiSwi7eaAHqRXBK0O8269VKcg93f2LZ5VPYSo=,tag:kM5rf3nzQaHsq5j03p9kwg==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:717PDYp+1Kx5gXly+P9JE65A7P7EnUZG7GbzN1+DxMGnXfUdtB8X2FyYKbCQMoUs05bZbD8Tf9R7xe1LFI+arg==,iv:9y8x3guRgXKqE4COTGzrRGqblc1GT91Bv7/gOru9aKU=,tag:bkhytYHydn8blmdRiFPBXg==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:CwZNQHEzn1eLJketu5XA/0VZ3hk=,iv:tpWM4MDHoqxQTuvcnryVSayiknAmQTij1i6m9VtuP6g=,tag:pART24cGlbm6LEIJxnoSrg==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:QnbFWe7S4blTPDZvKLFb29j12mM8wogF/lp73rOpUdIPYXRBhUMn/A==,iv:G3K1+6LEdNRhrFjTsf4JTZiQGhlfRjEzUUpD86vBYYI=,tag:opi83LDkzpSO+dEIqihYbw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ZQCuIEprhp/EmohoxMIZqlJ+ixXlemM=,iv:r2DOngo3AK4WmVS19JbiYVCxfFD8rJ2mBzDRGc9+EAk=,tag:VS22SgsMqFx9rtLQNW1oTQ==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:4GpyFQ==,iv:tP7aAPdhXOOj9rYw1vvgN8YdK1a6eQPRf5vzPla/3h0=,tag:UyLglhHxZlAMheLrye9avw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:OVVCuk0fWi5e,iv:alQ4AktY1jO0nwdj86Y+V5gfR7PDj9WfSsL3Sm5olgs=,tag:ZA8D9hNHhZ4hbPw/pBK0OQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:ajR7VPYAIXto,iv:Ni9NB4ZPLvCC8JtRRw7hSDI00AKvXTEUZB7c14hqqIo=,tag:zSraIs0bQPW598h/7RC7gQ==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:7/gUHJEef03iYM73DTyrzXCDlhan7agK/UOeWoLqOYI=,iv:hqT83Xtk00EFjVNdJQcrFm8hu+vy2ST9xg9/FvV0u2w=,tag:ZlNQ+CCqDwQOPOoR33seOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVFk2dHh4dTA5ZHNyYjhv
            ait2TS9rUm1vazZKMXFkcFVDZnFEVFpaN0RBClFtTW5SVTJWOTFOQTJMcXNQZnhL
            cWFlM3VxS1ZRaXpWMEZZZWdnMzJMODQKLS0tIE40Ym9mM1Y4S1NFYUtHQzRaK1lj
            Wnp1TjJvcllBaFQwcmQxcnd0dEhBQlkKTw8R8jQGIg3nQNxKC8Iv53Kq7TsJFr40
            Kl6izjLKfXKxwAol96f3w0/exnGKh/S47IPOd3k9veTsJhkcIOwFoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-10T05:52:43Z"
    mac: ENC[AES256_GCM,data:yCf3v2uTnwvPw4QIiwCdq1rvVwXs4PN9C3ZxQiYNoYNIm2uikdX4H7kpiFzfjFhQdGMN3o151Kv2lsfUnyEZ6HDr8X6kf3kxuVBu+cO4Sed4wQKZyoin1+o6XDW/+ePsrvNZRkNYEOhYtTC7HdvWzK4IeTXvBA8+Piv85JmgUNA=,iv:BCDrJVK46iaFeme5pWtnibsyRfDTGMPJoDcZcYZSjms=,tag:M0DA8Ui1pCZ4ghdRu8Z0HA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.1
