apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:FyKKuk80XxNryi3vEwySFFzU9qTXZCMNlposTbQZWnSuDcomyKPrq5o=,iv:Ssm0aA0PukO/kaLzwoJq0pXrXlcRnh3eqMc6ddz/+d4=,tag:3FIEk+JtSaXjua0//nHMtA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ztT6SWzpFxwUg+UiwGRqyOReyYPbEnMd+gWTfapZUzMm2pXPnzjikYeRLt7mGYj6pK0Y1KtitP9foFYrBWgM1g==,iv:2WJ916+CH1G8Ivx/oIhs17XBGxs93GHBPt2vbBOZgCw=,tag:FigiBd9DplZgC+Df33yl0w==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:C28ayrvhPookhE+18IUBcncfyikB1zsJLwo0gQyQXG2ZVyPw8RCpdsJ3n1LhDM/vWG46w2WhybGReh2XAMsmhw==,iv:ahYS7rlftR27BGIy7OoFZrRUeQLa9TPzs1cO+bgxrfk=,tag:P6ULB+uHzGZAr/Rvv84e7w==,type:str]
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:VShvW6+iorU4uVBhU7LLLKQ5/8E=,iv:QdOjntMvAzRhQZMzy2bOnyE6i4NzPFMRq1FpB7bTi44=,tag:RtDKofgjkXKkqBxX7p84+w==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:NvKwIBeK1CjIpkULdXglVYkUVL15zr/bzz3grsitnA00DLnE9Lqq1g==,iv:YerwVpxQ8+WbePajTtZxMB0CUcZlhB8cxgjtX22H2zM=,tag:MuGlqGFmGHqE3lboCXbWNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqaWI5OGFnT2hXS3N2bmRS
            cmltNEtmY25vc1dYYmFYbGZwRWRRMURuYjNzClQvYllCNjNDYjhsSG5FSGhnbVR2
            WWthWldaaHpwNTV1UE1LUzdmZWViVjgKLS0tIDBGRjhUbitjTjRCWEdTMG5meGxq
            Z0FBS0VxS1d1RUF4VkhXdGtFZ1kvN2sKHPnl3LdTtwzvWmiLkVyHypTLHz/sQIOm
            B3GyOd54pW3rlg3tUJryUmFw2p5s9gXp2gKuzbptWLah+g8eRtAntg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-09T18:45:53Z"
    mac: ENC[AES256_GCM,data:2lM1TbED6g5pJhzgkD/16wwiMJKSL0vAVe4B2uhCOoxJGQ/W8kH90+DrKEXtkf6eGMvMnp7LDCgH1nKfScCZh/ggw9vTZ7pi2MJ2akabqZUxTbDNBj+8f/lrZTSNUON3gITCVy9j9F78S8aCcjFvCcCmWwaVw0ezF5r399BiZh0=,iv:4DG1Z2uPtH04GYPKXjdRMSqI+KY2ZQnfrqOg/58TH/0=,tag:65BERuL+epuDMVBfva6sKw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.1
