apiVersion: ENC[AES256_GCM,data:Y4A=,iv:B57ehfVnKdGMBsDul7U/7FqAsnCldt5FMuRpQMP2M+E=,tag:+bfSuu36irJOiY3limakIg==,type:str]
kind: ENC[AES256_GCM,data:0/Z1094A,iv:FeE5rG3RNEFHVEahiPVyyIerChKkv507UgHSOL7czsY=,tag:yOMsUJhMDeOEGLm6pDgcbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UztQYEmoUnX/M69fsYRKf/c=,iv:V8dhW9/Hiu+MYV2i4mRmcqtYsN4e6h8zbcFOG3IUAMY=,tag:ydDGGbSIU+/X4QGErjOLVg==,type:str]
    namespace: ENC[AES256_GCM,data:1mv4GR/uwQ==,iv:ahsfusgeenm9AcErRXnzBFsAuchspXGZsLj5kmbalws=,tag:7z/XJ+KUxcaScQLik294dQ==,type:str]
type: ENC[AES256_GCM,data:UvlPJMW2,iv:W9qovDCHPvvNv6+wrjdAEo5S2kWsy3VysbrkSk8qmac=,tag:kkRUWW25sT4QZ0wMM1gz/Q==,type:str]
stringData:
    database-uri: ENC[AES256_GCM,data:VgRXp6xj4o+pQm20+MsWF0520mpfYpKz3VWV36g7VIQBJigdpW/8uk324reUIptQbtYhluNAXtsoVC0ON+Rl4W26VTQ444gCm7QP+27HTOztmJV7RhLMHSGjT0UfDWiKktH7Gw==,iv:lKVU6zpm6u6buzw/jsfBI7h2GCgemmC5XzoIqlQZS2w=,tag:8Mz1bL7e6Bt8rn1DQrSnuQ==,type:str]
    installation-id: ENC[AES256_GCM,data:rFV4AMpUajfrnmxG3FvDuXg6ICxH/CZvzSRw1oHKQtD5bkuh,iv:HsNV4k2Tqh5iM11fqCYkfyeVKCq67865WSLzIABm26s=,tag:gP1Yj5hCRHeA9W6s6jzTjA==,type:str]
    installation-key: ENC[AES256_GCM,data:E26Drsiw7i1HoJdebYGLF/37o5M=,iv:bTp8ST2lw7AoippExYUEPq68B5zxUMkh8FYnqpoW6J4=,tag:idbUKxUyr45H+qiZ9YB6NQ==,type:str]
    admin-token: ENC[AES256_GCM,data:i2/zMY3H9OpBVdCPqZAGrXpmKiVAvoLKs+mOWhsQtZDoNZrJfA806J0pNG/BpDMI6vvtbpLQQX8pIaKhQ9JrMQ==,iv:bKDlkywFmM2UU8jlP8VPm0dfbukwEDKfgrSVklKPyiA=,tag:fGKcu9cyMSKnOWb2o0yylA==,type:str]
    smtp-username: ENC[AES256_GCM,data:A3GWihEtLQklsHDm/zFK8iw=,iv:IC3DM/73w6WNmx4I2x1u1CLtTQECVUDiSQRAPi7r+xA=,tag:5TcvCPjFpIcdmRt2OGfxKw==,type:str]
    smtp-password: ENC[AES256_GCM,data:7bsATUr+BaFvQ7oJ68GXnVgUN4Duf69anPyEyraFYVQ=,iv:AZhYzEWPbjNQodsUGpwV7EYfoKktRwA6g67MszJz0+c=,tag:ZeybKT5qYKr1xch6nwYI9g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM21Qb1F2VDNjb3BnN0NV
            Y2Zlb3VzeGIwRlAwcmdZbzcyNzdTdmVFVGhZCmR0UFZFOUV4bzZHU2JIemFhWVhs
            KzRVanBtdHhnUlh6eWRjQTN0clhRSTgKLS0tICtwM2o0bFhJZDJCaUVIeHFINnY4
            TThNVWk2cFVtT2dBdGJiSnE3VFNFRjgKcSn6284J/pFJs3GegJtmVP0QYKmun4P0
            ggOzXTNNER7hKrSYJ6I96WG1X+/RCPinUySAXrkghy34QO1HU/1www==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T09:36:58Z"
    mac: ENC[AES256_GCM,data:Jex6geJqkpyukJi129ZItwa79UFzPImeTv8h+FyIqBl/OKFTBWJW5ylbAoBPnjJ7neSXWjzKKLeS30DlYiLSwCW9j1CTEDSmFwRislsfIcUPnxAuPA+Zl2zC9BD9qXpZ4WmVIembopekPnn7QNmDUPR5WOIwikaEVReu7oNFGHs=,iv:F/6YJ6s0YUbPX5HOouilR2naDMnxFEUurR14Ixn9XB0=,tag:WMmUo4zytRNeJM9K/86V/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:Y4A=,iv:B57ehfVnKdGMBsDul7U/7FqAsnCldt5FMuRpQMP2M+E=,tag:+bfSuu36irJOiY3limakIg==,type:str]
kind: ENC[AES256_GCM,data:0/Z1094A,iv:FeE5rG3RNEFHVEahiPVyyIerChKkv507UgHSOL7czsY=,tag:yOMsUJhMDeOEGLm6pDgcbQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bi8iJ/HUVYrZPWoXdVjt0AbhFdGVFBA=,iv:A5D+NYpM1gvcGtb04Hp3ln37NbCau9wzX/Q0vY9huyI=,tag:l6mLIIItjQ9NATJjHrTOUA==,type:str]
    namespace: ENC[AES256_GCM,data:1mv4GR/uwQ==,iv:ahsfusgeenm9AcErRXnzBFsAuchspXGZsLj5kmbalws=,tag:7z/XJ+KUxcaScQLik294dQ==,type:str]
type: ENC[AES256_GCM,data:w/SHSpw8u7T0/3S68lduS6tkUs37zR2Z,iv:mq4XA2vEGMQlBXaGQjZlxxXswQUqYQu4FSktWI9HcHQ=,tag:EFuRtOnHmdYboyEtBIXMnA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:PReYlyPpjFU8u1A=,iv:yP1D1lhbnShtInYuRRr56LBCDbuEPzXzdirVYrYpxUo=,tag:Xn8+IIpOK6ND7FVsUeE3nA==,type:str]
    password: ENC[AES256_GCM,data:FuvrcTXZImfbZg0YfdBIOmgzW/+k09TPAzg5b09GAY8=,iv:csHCxmv+rYyZ+clxHk+/soOuQcvD9OlR/4sn/JRHD0s=,tag:b6ZjFDalRCC6MChgVYmYxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtM21Qb1F2VDNjb3BnN0NV
            Y2Zlb3VzeGIwRlAwcmdZbzcyNzdTdmVFVGhZCmR0UFZFOUV4bzZHU2JIemFhWVhs
            KzRVanBtdHhnUlh6eWRjQTN0clhRSTgKLS0tICtwM2o0bFhJZDJCaUVIeHFINnY4
            TThNVWk2cFVtT2dBdGJiSnE3VFNFRjgKcSn6284J/pFJs3GegJtmVP0QYKmun4P0
            ggOzXTNNER7hKrSYJ6I96WG1X+/RCPinUySAXrkghy34QO1HU/1www==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T09:36:58Z"
    mac: ENC[AES256_GCM,data:Jex6geJqkpyukJi129ZItwa79UFzPImeTv8h+FyIqBl/OKFTBWJW5ylbAoBPnjJ7neSXWjzKKLeS30DlYiLSwCW9j1CTEDSmFwRislsfIcUPnxAuPA+Zl2zC9BD9qXpZ4WmVIembopekPnn7QNmDUPR5WOIwikaEVReu7oNFGHs=,iv:F/6YJ6s0YUbPX5HOouilR2naDMnxFEUurR14Ixn9XB0=,tag:WMmUo4zytRNeJM9K/86V/w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
