apiVersion: ENC[AES256_GCM,data:10Y=,iv:f8YGakIA0QzXfm+kzOMQHxeUcSm+gropuoEMTSLnQt0=,tag:9qjePubap4KDE6wSbX+aTg==,type:str]
kind: ENC[AES256_GCM,data:SfXvUym+,iv:H8OIRo3ST5z2cZH8j7dbcKgF30BUwnI8vDxyJLsfmfg=,tag:ZtmqPosqmBF9OCIYEsB/lw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1YzAzvj9CC5o/FygNMGC,iv:fcmyGToSp4KdL9jDYLIBhMLPTcFtFqJ89MDhbpFI3ng=,tag:Y7Kr+fH/z3RJziOUukIEdQ==,type:str]
    namespace: ENC[AES256_GCM,data:Ou2v1P13bQkQTKk=,iv:nYBwDwsh9keSbCIIRND+vFJ1aSW2Vf6ljCuxY8JL6jc=,tag:9F0JtGfEEv71mwB4to63pg==,type:str]
type: ENC[AES256_GCM,data:KMg2rlaL,iv:lch5Hftlm3kjojpDKbuCkHQDM5L3y0BLKyQU2a6rQ2M=,tag:HaI2/ZlL0HLK28u92EjAZA==,type:str]
stringData:
    FREENAS_USERNAME: ENC[AES256_GCM,data:tjxeMQ==,iv:9a0hq+k8KWpjM5Zm5apq+7VEjesAZzqCQ3H4G5tBBCA=,tag:y0ShDksLF6Ieqoj9GDaOPQ==,type:str]
    FREENAS_PASSWORD: ENC[AES256_GCM,data:G4oApolVVRuA5WonqH2kBDuqvg==,iv:W7HAaB3ZlcDDGTJjOwTHi/VznJbuc7CKIW9RBuTtjN8=,tag:1idvQnNP09Fb9/UAsQSCkQ==,type:str]
    SERVICE_DOMAIN: ENC[AES256_GCM,data:2Pj/uM7CHDWlbVpY,iv:qirD/SV2HpteeBk83PAUde50xWN265/qg+xkBP6Sec0=,tag:oS+vNp/hAcLE9/dj+t0GsQ==,type:str]
    EXT_DOMAIN_1: ENC[AES256_GCM,data:WrQprg4KC4WH,iv:Kwqqho0hj/SBJX04BMI3urL7QDp/98bbKkGHVU86rIs=,tag:kUdvw7s4IdGEZla3LFxDfA==,type:str]
    EXT_DOMAIN_2: ENC[AES256_GCM,data:NQ6TjeHNqkk=,iv:FrTzajpKoQXUZ+n+M4Z6E7TZk8uEWh3zz7dEPkWBdng=,tag:PnUgGHUU2xPXXfff/wpUBg==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:BjeqpGrGoZMFFILNlr4=,iv:w7lUjLX8Va09tKGlCMhclif4fTfZJ9PFBDQv6N7PvHQ=,tag:1uLJ9JXXucBGUE1GQ+T49Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc0NyK20xcGxMUFc4WGNz
            a2x4TmkzUnZBZkVoaG5yU0hVYndVTmx1bXlRClVhdUpvaHZFYzRwVkM5YjFIcmIr
            ZjNUVlVXdzFxY0F4VlpEYjlaNVB1YWMKLS0tIHZPNHpIY0UwZlFNZndxdy9aOThJ
            bllHSVpJY3cvYXEyYWViMWt6YkN2TmcKPD1o9pYZKevz3o+BxTU63srPBBCa6JV7
            5mIhXEd6yc/7qtBS4HpIj8qqkrNjHrlK6ls0ftlFuuSsZFIyEDKq6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:29:36Z"
    mac: ENC[AES256_GCM,data:tWkUhc9rr5dr0bYhZ2GW6aF+wQnhvLDn8/aZenztjJGEIdof/+PMyQUIBd9JuiFu7i53WmMzPX/N3S231b6QTJSMV1nr+Wafsu4uNza2773hamFOVWOy+kIwB96bE3unMuUqfjAIsKylQDE2LFueRGmy3X8Nqc6cz33RcUB1tCw=,iv:I9Sx2qyOggwqxtB6I0bQuyvexyf4WJtfRCa6xP6gNDM=,tag:HK8EV+ewjhAHSxKG+gstcw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
