apiVersion: ENC[AES256_GCM,data:zuA=,iv:00anhe0mA74OdsmYoCbFv4V7/ZWVqQGDtAl7Q08YDIk=,tag:MIEc6dbppOEePdlniEI7dQ==,type:str]
kind: ENC[AES256_GCM,data:fcfakrK1,iv:nzDK1WpA62/o1nFb4Rde9SyfF4Tj87AKJmbitI+BQ8I=,tag:/uF/aWwzKgR/XC/iSZvCfw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0D9Cki/d4MhjaPj9TNV+nRzYxc0g,iv:tkhnJ6kgBJGAEVHQSUrwUjJaIj30O5vQwHB3tJDj12Y=,tag:Ry+cV4J/If01e7/+ekAF0w==,type:str]
    namespace: ENC[AES256_GCM,data:xCe/zdDSfg==,iv:9VMS5B3hyW56KEuAQnpika8WqBLHIcj59wfw5KKN340=,tag:GX8YVxOfl5q4F3V2rujncg==,type:str]
type: ENC[AES256_GCM,data:53WqAsZ9vBZEJIVRksw1idJwFgFQhjfd,iv:vYbUCZ5MzQQ70gsu9KMHPmbOnekFR6qaPMBiPE91kxc=,tag:q7516DBM6k493W9CjmTM1Q==,type:str]
stringData:
    username: ENC[AES256_GCM,data:zAIexpAEMA==,iv:XF3Xvbwvae3U2du/HiT8txhyeA1EUl0lp6Rp9rLimEw=,tag:xgHeJbFqpCaszGdl7vUPfw==,type:str]
    password: ENC[AES256_GCM,data:9TFVfMZkJSLQV3VwEIMTVXMtsRiaGcDrg6URBbnPQ9M=,iv:dXgsiFA+H0U0ut+jV1O0rMWZKpabblYg3+m2fWsKldc=,tag:s43YqFnNJGPTv99flOCARw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd09LbEx3dDlLeEhUTjhR
            THNHOCtwdTE2d0pCOW1FRFVpVFRQUXM5T3lZCmNYWjJ3MEhVRHlFSHAwS3JvUWRl
            dlhDUWJSb2E0emxNbCtHQzI4UWZUaFEKLS0tIDJXTXlzaGVQNFhnTk5WTytIdGpU
            UElmUFp3OExxTzduUDRLZUJHMVE3ekEKj+YTi4KjPOSCqRM6n5icVkCamTBL6O0j
            9NkAKX6tf6kqD3AIfDRUymX9BZatXhV9Ax/hUkY0yCTNXtYX/poK7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:32:40Z"
    mac: ENC[AES256_GCM,data:oUM48UoRBHR0OXHlBZAY9ILboKVtMetTRb/N1X0z5oSsGdm5ABoedYy13YfnPf2f+zvSAO7p/H3nq3nPmXl2dHn/NYQmDarOo4UCDxp3LMSvfJqH/ZuqtBniXMiFSKm9THyDoewPPPL1MMHSG88Y+BSFVfOsS6e2OcqIgc6VMC0=,iv:noqZuJ45+kUfmrWQqmXP1WY+zgTZdVZlJM+Vv5KChaw=,tag:m9jaMipdtD1KVu1nISzjNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:EVI=,iv:lBr2LrKG4Pu/9w7GmIWO8S2SZJrm5krm4FXfsHEVvnA=,tag:L+7zHSoE1q5ke7oU9Z4Wfg==,type:str]
kind: ENC[AES256_GCM,data:19DZ3P+Y,iv:RIz75EEdsJJ1j/wz+djrSxfmEOuNU4ZbMZfCNq800+g=,tag:qxNI4XxuSg9pF+7x/SVrtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xGJYyyVoiUfao8t06jI=,iv:1Oej3bwg73Pd0Rq2nWyEBIw9DkFFEhgFIU1vR967XpI=,tag:45y3uVgXsHvhw4UZTSjgdw==,type:str]
    namespace: ENC[AES256_GCM,data:C5GS14b9zg==,iv:n0F4p5lvXAkrGbESFYvhUSJNTeP7+meQzBwhrHbRkOM=,tag:12q8+q/abf3uBbsmse5LJw==,type:str]
type: ENC[AES256_GCM,data:e5ivSTZs,iv:6Z20wkoesZUdRXjyWpJiXODcfJi/BAYXBuPQeiRkNtE=,tag:4H1Ad4fZN70rrU2lOLyR0g==,type:str]
stringData:
    DB_CONNECTION: ENC[AES256_GCM,data:UVuslwg=,iv:vGcjsd0FwudyUSVapHJWJDottqBW/xlnhSsvnBUXV/M=,tag:Ry5jbbzht6JYcdNdZIh9RA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:cThAX7LXDERlh7UgyjjPQ4eBlxMk,iv:U+eXlcuVQH3LcIq0Noc8VQqghznCiyOlA46oBibS71w=,tag:qc5ZkXA9RXfq/q/5v0Bjlw==,type:str]
    DB_PORT: ENC[AES256_GCM,data:KRFxjQ==,iv:WCmsxWj3QVG7dcOOAsgXBS6wbUO5heP0EnLGuOGZ+yY=,tag:N4BzlGiW+z4EDOGJt+VaLw==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:tw7I64B9IA==,iv:zBeGPzKA4hcBO1CHrHz+Z1QZkj9oULLzDa+4pBCAQYk=,tag:B0nEBvBjpaezGMTPqqwZfA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QkXaFnOXmPGW8Fsnv/rgsD+t1vRvdPnneGaQ96T0DYI=,iv:QmqSqhXQiWwd58eoB0Eqpem85wSYsVjHPSl5KeS0nfg=,tag:zcO4GLrDMkjbvH5lSBOyBQ==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:H8kymHft2w==,iv:yzKHL0Kttg69iWrhtI1gq9q6fO1ssa6/RA0s7zb/v6s=,tag:u29CPxufLVcIdJCGTenHtw==,type:str]
    APP_KEY: ENC[AES256_GCM,data:+DXE5sGUFOLuhnrF8PErZ3mcsoMOcvdbsmnjYNY4nNc=,iv:jVfKQEIPMNjVd/SzJwq7kW46q0EpnwIQ5kfy/AaY+iU=,tag:LM7fLmnDzgh1Al71YKAosg==,type:str]
    APP_URL: ENC[AES256_GCM,data:ynov4nxsBEp0nj1uj7DtH0GOEqk8FFFZp1zQVA==,iv:1NN5z7MPdC/f8l/9pgaxp4fghd2BViABt4wexY8ydNI=,tag:F6c5aDGXfBvRbrPFPEtM2A==,type:str]
    DEFAULT_LANGUAGE: ENC[AES256_GCM,data:SU4DLPI=,iv:GMd6qUhROyqod1CZDlPhtXIZt+NXNfqUhgJHLdtrlLI=,tag:sW1CSIgJu8eMwnQURnsBeA==,type:str]
    DEFAULT_LOCALE: ENC[AES256_GCM,data:FxV+w58=,iv:NKTUGQz7aNi/DkOD9pvHXRx5xNLAsCWBF4MntVLy78s=,tag:dDoxrdkrJSWSQnaBhmDoQg==,type:str]
    TZ: ENC[AES256_GCM,data:1yL0kxsERSADvQ98pA==,iv:PS5DwdjaaB+N1C9b1P9OWqgyyLGUAEJ0pBg24DF+wUw=,tag:mqFGs12jQUCT5UgX3DP+FQ==,type:str]
    TRUSTED_PROXIES: ENC[AES256_GCM,data:+rE=,iv:VWKKk1ol6XnHFnNw21UXH0CZPe5MvZ3rP1gwq9wLglo=,tag:QU/4YLbCahigURTVKOCM0g==,type:str]
    MAIL_MAILER: ENC[AES256_GCM,data:XtjCtg==,iv:t35dgpE0fFfqE4tDcuEFHeztKEQmmpz1808xAYu1h6U=,tag:i/hCpX4xHLejJ8g6OrGzfg==,type:str]
    MAIL_HOST: ENC[AES256_GCM,data:bDZnmBK0DXNWZFvOvzA=,iv:ckBMyOjkLnnGMGrTaP96B80HZLLGzcyOveP47yRQKW0=,tag:FrYxJwwMzNmT1dHepWxnpg==,type:str]
    MAIL_PORT: ENC[AES256_GCM,data:OsU=,iv:n7nwRf6mmTsCYUK1rsTIfMP6vJiQRzoSp1BpT072sDw=,tag:+9xCvSj0VZEqQViFjt+ccg==,type:str]
    MAIL_FROM: ENC[AES256_GCM,data:HpU3SlBZiX5qa8LRtL96xb33J0c=,iv:PbJKVEfyi16VEQVOBAGFSqsxR7UuylKk0nA9Qh+w1zs=,tag:USb+BDEHKJJnIQLUb3QYaA==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:Gl3nnCZ0S43Yrk3GNr1zUD4=,iv:rEGQbuTJ4405Sm3QcWhjCX7GOrmfvOsOsiL8YKMwUZ4=,tag:nvr7azIjeFqy9frZagBDtQ==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:w9kIQujDLm3gNLFzQn+RSflTTi5dAJKnJQsDaMuAHgM=,iv:aA+9bApfILej2uVLjLA8z1opTYEoqqTjQzIyAuALf3g=,tag:5FmVdriuSjaX1fCHTr159w==,type:str]
    MAIL_ENCRYPTION: ENC[AES256_GCM,data:Ja3B,iv:k0x8o8xDKMnfd9IaTKsO3dECM5+LnWAxXPX3FNL1mV0=,tag:thZUbxevjBzjBUefU+qfsQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd09LbEx3dDlLeEhUTjhR
            THNHOCtwdTE2d0pCOW1FRFVpVFRQUXM5T3lZCmNYWjJ3MEhVRHlFSHAwS3JvUWRl
            dlhDUWJSb2E0emxNbCtHQzI4UWZUaFEKLS0tIDJXTXlzaGVQNFhnTk5WTytIdGpU
            UElmUFp3OExxTzduUDRLZUJHMVE3ekEKj+YTi4KjPOSCqRM6n5icVkCamTBL6O0j
            9NkAKX6tf6kqD3AIfDRUymX9BZatXhV9Ax/hUkY0yCTNXtYX/poK7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:32:40Z"
    mac: ENC[AES256_GCM,data:oUM48UoRBHR0OXHlBZAY9ILboKVtMetTRb/N1X0z5oSsGdm5ABoedYy13YfnPf2f+zvSAO7p/H3nq3nPmXl2dHn/NYQmDarOo4UCDxp3LMSvfJqH/ZuqtBniXMiFSKm9THyDoewPPPL1MMHSG88Y+BSFVfOsS6e2OcqIgc6VMC0=,iv:noqZuJ45+kUfmrWQqmXP1WY+zgTZdVZlJM+Vv5KChaw=,tag:m9jaMipdtD1KVu1nISzjNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:lKY=,iv:laQbaDLpI+cq24jlIIRWm9mHvbqxbG7bRvX9/Up/Z2k=,tag:PLitzm5j48bkvmIEZD1c2w==,type:str]
kind: ENC[AES256_GCM,data:2SVGopq7,iv:FUTlRhPsT1anlHnMvW1nx18YJoT1tLeoO28QUsAi1lk=,tag:jB/xO6dYQ1zx+M/lXnyP3A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PnO6XzFYbN2Y+xcf,iv:jatoxJrkix0inLtCfXqMv16uVGgH2Vlb5TfXNIRMuMw=,tag:yu26KC27kRMWsE3CScnjag==,type:str]
    namespace: ENC[AES256_GCM,data:pwLSmbVKXA==,iv:4kwX2x+BbfDDU977LAx8M4oKgLoGBF8O/uVmoUYlc/E=,tag:oQARtomYUGHGKScOOoza5Q==,type:str]
type: ENC[AES256_GCM,data:6vUN57QV,iv:wnOmn3M9qL4Ab0nZp2JSNOO9HbgY0TY1F47bfusBeKc=,tag:K26+4B7b1CwOVrKF4S+JJg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:KKYvotneO1nT5THDl6fxTZzcpqglFdNqr8nC4XQBgiI=,iv:cFQvTE43EcOM9KAzeQmcMuZw1Zc1fwbXWqfkoJ3bNuo=,tag:Mh488zRL9mT3Kq2bIM+wXQ==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:7MrrSRh2y2thohXE8wvbzqxa/hFoKawfvfirVbu2o1EYQ6PeUCEg2ky/Gf1jJzN6jtXhXLsWGEe4iGIC4CNJ0/Azsh3zJj9W2TQzhfsHQl20TCeT2e/nYxlsA//BGg==,iv:fnS53MRgwVLqy0viEsS78ILZytSIpwgeQioG3wkwG4k=,tag:ir88Wv/YmRB88xGi6mt/UQ==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:OposLjhzq8o/LSqBjGJYK8/i5XFvd1QdUOwF1FRlHf+twAGva3HllGBOtERCdJEK3mMSccnY6bfW19wonafMJw==,iv:+DVgZ0Eh70e4xrEeAMsrKbbq0tXuQfKsVcpDY8i0UtQ=,tag:Tov2AsnszHrL1gyQFlPvtA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd09LbEx3dDlLeEhUTjhR
            THNHOCtwdTE2d0pCOW1FRFVpVFRQUXM5T3lZCmNYWjJ3MEhVRHlFSHAwS3JvUWRl
            dlhDUWJSb2E0emxNbCtHQzI4UWZUaFEKLS0tIDJXTXlzaGVQNFhnTk5WTytIdGpU
            UElmUFp3OExxTzduUDRLZUJHMVE3ekEKj+YTi4KjPOSCqRM6n5icVkCamTBL6O0j
            9NkAKX6tf6kqD3AIfDRUymX9BZatXhV9Ax/hUkY0yCTNXtYX/poK7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:32:40Z"
    mac: ENC[AES256_GCM,data:oUM48UoRBHR0OXHlBZAY9ILboKVtMetTRb/N1X0z5oSsGdm5ABoedYy13YfnPf2f+zvSAO7p/H3nq3nPmXl2dHn/NYQmDarOo4UCDxp3LMSvfJqH/ZuqtBniXMiFSKm9THyDoewPPPL1MMHSG88Y+BSFVfOsS6e2OcqIgc6VMC0=,iv:noqZuJ45+kUfmrWQqmXP1WY+zgTZdVZlJM+Vv5KChaw=,tag:m9jaMipdtD1KVu1nISzjNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:QnI=,iv:5+jA7iWzEPvXIjMTFtj+45SfqETy2uyemJGOsCNn4a0=,tag:r1243H8I40MoCs5vXnrylQ==,type:str]
kind: ENC[AES256_GCM,data:MaEwcSJY,iv:22Kot+W3tmMbKwRpmtIjXbvNUJFcT2tZm1HGG5QRVsE=,tag:Srtnfs9U+co51wJKPOdzWA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ZRaMYWrRq8pWZnYHPNQ7bA==,iv:Bspx11Yl2c/QE20ntxKlH5HE/9//tdDHP7RJNkrbcZg=,tag:QWg8XLVOU83uVtco7/NR9A==,type:str]
    namespace: ENC[AES256_GCM,data:OA+5NsBa7Q==,iv:3+pHpSNTpd7qGjo4pxx/j8934TJnNjkKH8jbMXwYHYg=,tag:PUGV+vnH1Un0NVTc+MuTUw==,type:str]
type: ENC[AES256_GCM,data:ZyFxNlzq,iv:nthqpwQEmtdIpY6hFTkZrdfaNfTMU/t/sZLrqDapxns=,tag:zvqBhoFW+peqYkHL6Hh9Ag==,type:str]
stringData:
    accessToken: ENC[AES256_GCM,data:A2PyPLvYThqjBW+m5UJ6G3xmos7VaQWEzq8xkwzmTpgrOkR+eDcEnxGWKA+VYE38ZyPfJnz9C3Y5Vj/GP5FylHtXRAEB2QBZzDVGmZv2ROoHMA8lNaeQoaXm751dz3DMd3Yofon0UmXugVguiXlYGBEC478HbX3zEBTQfrS13kfXr/OkyxAqOe2cU7V+wfXU02aGp/QIYiDNmQ1JvYpJ/RbpuxWkUT8n8n9vtaHBsHfFJTsBtLitcmuLPE4N+6vKJ2cQXSVEHf16qHuHoGc6sEsd1Qj90g/k8a5lfj1JH7rcCfaZYI8A4o2cixWqt3RobpnHrS7b0UdoPecsk5OOaRRbApibe6xCTPrSLpbnN9TrZ3OT9HVQDz4aZERX9H8xkXsLmkaubdTNemOK1qsGRWhMmoDftYMiS/N4WjWVJicRLCLFN+nzIgCqQGLqU1szf216J34AcWB7+/LHFUvN34/Ng7OaggwkHjdzKuAFS/Ez6tB1DMXfEROUgRz2y5ih0DiMt25nDNZ1pBLjsoBkXENwfV9+9TN2csmtZ9qZ4t46X2f6uSua1MGSPKqmIx76P3jAzxf18GWtVIh8qGf3OhnVli9UfUiieM5d6TGApDZ8rpcHTQA9wruVOCu7cJTFRQUYL6718EYsqKHQGVvCPHF/JtMky1malU/AMVZDC8D/KWUwydcrYMezwvjMmnBrz2/QKu4r22tjVEabHy4fLFwTb0GDdCHBWj43rBa1MN+biumHhubd82O47TlyJHY3QT9ZKSBgPxOjDcQRVdK1QXD3cyIXv3NaTI4HV7tDAbyeV8ZwKax//uIFNnETQS/DTy1FCH4yGI3bViv6bNdA24uHs8/G6upSm7KPwTVST72WrK8BDfe9sGjmTaRvE64kbExEN1rmqfbTQIUn467kVvvaHXsbDlUU1P4O+FkBjyFh38gpvhqH/delpeQRrfmthrgp3TBKntp2S48pjYvLjPH43tnDbIhnUw4MlzVeXdms9QP+rkMwYqbvvg11NEciF2vxl5P2K+dwYmKsGWjrRJrMmmeoRqIza6M+wpMftJJfpJOckyoCmkM0ACnvVoJ3XjwweiDCjnLhpiJD6QFz7XUa2i71lCOjPP+6ySEqrpRZh5GykUBiclm+AtmXBQu7Dbsngn1HCcc/g8jAMCs/j7+lKOHAjdl9aNEi7We/GmuujbeE+hKTSStll+dqpoTigjbugUC6x8Bg6Kmd3csquBa0aUWdR92n4Na6wN6wmV2MUVgOSsrDbnsW7VpnxNh4L5bMw3MpbjZYilas9EnDT+z3KWOp/SKq,iv:OLh9ipW1WBfbS/Kn0S88IiFsZV5AFWgWZDMNyerUP9o=,tag:BQNPJuJB4bp65z0FRDMacQ==,type:str]
    SPECTRE_APP_ID: ENC[AES256_GCM,data:Jv8MkORG0h/rD+HGABZhrbMPw3mDyCBiVrheb3kTLdgX9jeI66SI9pyYGA==,iv:l4y91WbUSYkn/ll4hWzq88vvo0y7NM5mtG+rORdG2fs=,tag:UcK8GSap3G3CGRiviyBfzw==,type:str]
    SPECTRE_SECRET: ENC[AES256_GCM,data:wXN6gHesapx/cqYnrcpmjgJJpgOJ4N6hCJxManOlUmv9AAvap0YgpQDFSw==,iv:cEaKEYzA5PpJxzXbZbpKWl3LGsPCqhwrnkcaHqzRHyE=,tag:o8GF3/JnYpk0ZsjL/4mAJg==,type:str]
    NORDIGEN_ID: ENC[AES256_GCM,data:oQY30Obx8sq6i3IsyaYNqeqEA+lp34ewijqsKeMHX1cjTVSZ,iv:Q4pcj6qFyZV2yf0WjSbLAUTVhlbfYhqclxYA8VNUpCk=,tag:hR/3bjwEiDE+wrLGckdUMw==,type:str]
    NORDIGEN_KEY: ENC[AES256_GCM,data:EzqnOJoQ8Ii+RWm4vEKEwtZg2L72nbbws1zITnO0vjQb9x/laJV4QDaZFdGaz+LROHN9YYGBHwQ/BQhml9/O1+IEdWFD7vru9UaK7jHLsTl6EAnYsLV1RIfso6AG+n6eYW5D3YyWlnryEjbmtAmg1aDS972izrqgFpxIUq5sw7k=,iv:uwdEBo+nAKqwkii3j4z2epwH0ziYhtAuEWMylEP2dg0=,tag:80gvJTaIwn0/lzqOfLKLYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd09LbEx3dDlLeEhUTjhR
            THNHOCtwdTE2d0pCOW1FRFVpVFRQUXM5T3lZCmNYWjJ3MEhVRHlFSHAwS3JvUWRl
            dlhDUWJSb2E0emxNbCtHQzI4UWZUaFEKLS0tIDJXTXlzaGVQNFhnTk5WTytIdGpU
            UElmUFp3OExxTzduUDRLZUJHMVE3ekEKj+YTi4KjPOSCqRM6n5icVkCamTBL6O0j
            9NkAKX6tf6kqD3AIfDRUymX9BZatXhV9Ax/hUkY0yCTNXtYX/poK7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:32:40Z"
    mac: ENC[AES256_GCM,data:oUM48UoRBHR0OXHlBZAY9ILboKVtMetTRb/N1X0z5oSsGdm5ABoedYy13YfnPf2f+zvSAO7p/H3nq3nPmXl2dHn/NYQmDarOo4UCDxp3LMSvfJqH/ZuqtBniXMiFSKm9THyDoewPPPL1MMHSG88Y+BSFVfOsS6e2OcqIgc6VMC0=,iv:noqZuJ45+kUfmrWQqmXP1WY+zgTZdVZlJM+Vv5KChaw=,tag:m9jaMipdtD1KVu1nISzjNA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
