apiVersion: ENC[AES256_GCM,data:610=,iv:sxE1uvp+Dt7ATyLTpgsQZYI0OKps1Ne5tCb0Y5ObBjI=,tag:Omg72a/Gb5NK1OiIVVSIRw==,type:str]
kind: ENC[AES256_GCM,data:UdLQ1XxI,iv:vxnwAv+XfiB/wUDuRibyfWfWoeGb0ySa178D/HAIRUM=,tag:R/J7Y1LzvRlTrmw88djmkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:G/byzcApD10+ZlrA8/1P,iv:lLcNYH3F+ZfyzpjHe7NqYj+nEweZzzGaTxStzhSjOUU=,tag:15QldF2/VIDDm4JV5H9C1Q==,type:str]
    namespace: ENC[AES256_GCM,data:bOym+GPwYxk=,iv:WgYsUjgRZRkB97JkPHc8LfYeKpSsyq7We9HCq5ORkgo=,tag:Bw5QDBr26phRs4HBNbXUeg==,type:str]
type: ENC[AES256_GCM,data:LKVeMIZD,iv:JV1Tmx4pnORBxAZQY8tn8JdfQY4bSIHAxJ0TPkKIcTc=,tag:DYiaNp4mLMOfYVHPuDlSPw==,type:str]
stringData:
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:3AwbCfxlxTKBHTn5x3aScb9P08KPa/k=,iv:Xjfg3Tcz9peSJSc+tHkq5r3gV1MwomN/kUGqiKdsZl8=,tag:+OPvvGoX+V5mNg6lWUfkEQ==,type:str]
    VPN_TYPE: ENC[AES256_GCM,data:I6JHAAmLGg==,iv:hEkXKJFbCkHkzVCVjBQZ3uEJBM4bIvKC3ML5I5sJ1hY=,tag:/QoH1cinmcIKVPk0jGffoQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:lPhMw08ViYA=,iv:2pNDddhGMSKlNoJrp6HLl49LI3L6m4BtUhVwFZ/p+uo=,tag:TgvwUoT3bJYPjwVx+GM7lA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:PKV40JyNyzSnfc7L1GXeLGmhqN/S1yNyJPDGHWZxwk0=,iv:h4dnF25vjr07QnexwhRKwnPLT/kU0WeNjEjgBkYWdrk=,tag:2WL6kS+v3RN6NccbEWfAsA==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:D7Qa3KOzqNytEBM=,iv:66cP1hwDEnxTYcyI4Kmn0GCSCf3fXYthFLRWhBulr2A=,tag:2juMtwmrSwPXC3NDC4wUAg==,type:str]
    PORT_FORWARD_ONLY: ENC[AES256_GCM,data:BLHW7A==,iv:a+n/006ZPMzKh0fV+t8k9Ck6fYdBmhf+MmK5rXlbDjo=,tag:tvjxU/aw3l06lNLpFSb6gw==,type:str]
    VPN_PORT_FORWARDING: ENC[AES256_GCM,data:aqI=,iv:b4d2ojU3qMNbpPWaEA8q9uu/2SR+voS4OWz/P9DAtQs=,tag:uJ9LYSg/pUdbPwK9bv6Z8A==,type:str]
    VPN_PORT_FORWARDING_PROVIDER: ENC[AES256_GCM,data:3gJ8ohbKPjpUxwM+CqrpTJOtb5FurB8=,iv:uPFXxyq2pWkv5nfPIvRmntmDxj4kH8BZQ4c1fhvgJ30=,tag:b3a5jMUA59NFCSXIBElONw==,type:str]
    VPN_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:AU4dYxYqj64=,iv:J2B9DSYZ0M2xgJqLwM3aHbzhFSKGyyDz31xrYwkLJd4=,tag:O1ZdhMN6zQ51mU7tT4pkSQ==,type:str]
    VPN_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:qLZV3XL4Kot5OVpI/VgibyxV6WmedYQ0l8jtiMqLoxs=,iv:XsXabwcVhKcr2X1umKNaL8sNWYQ+x1/z2ukBTeAbNFM=,tag:sYvkRLXBTW8JtgiLNRbEyw==,type:str]
    FIREWALL_INPUT_PORTS: ENC[AES256_GCM,data:bs8mXqbpd8AX,iv:MZ+qfBeTyuWJVxTBInVP9dGUqSKEhKB5eTAvFudRK0E=,tag:2YPdSN1z0T+TVUqgy5uKBg==,type:str]
    FIREWALL_OUTBOUND_SUBNETS: ENC[AES256_GCM,data:b69lNf1ZoaN3Z7CrTMxipchdUwQRKc5sW6D8,iv:AJVzPUYE6wq3ZluAjRZGQa2q1k4NtGLdu9tYU21efbw=,tag:spIP0b9viCWWQCxzmXTViQ==,type:str]
    DNS_UPSTREAM_RESOLVER_TYPE: ENC[AES256_GCM,data:bt82UB4=,iv:unZxX4lwdaI8iPVW97f1xz4TzxQAYcakLuloJTCSDIc=,tag:ibK5ywB6cYkhDAcalBcQnw==,type:str]
    DNS_UPSTREAM_PLAIN_ADDRESSES: ENC[AES256_GCM,data:ixpqeqmcQ097UQ==,iv:Jf58ObBJImdmf9FtH95uY0Nb6GHbp2axE2qE4MrM79c=,tag:aoiy32A6bOiP8G7d4ZiDNg==,type:str]
    HEALTH_TARGET_ADDRESS: ENC[AES256_GCM,data:TqBpsdU/XsnSd6E=,iv:Aznz1lrHv1IYiMsIOZQWJ+BWjkJn+bE87bzyp9LyxL0=,tag:cM9s7GZ5SIB+9tO3V2zKpQ==,type:str]
    QBITTORRENT_USER: ENC[AES256_GCM,data:wQ7vZZE=,iv:bXiXYIwjXL8zaNIKGehmrjjjrAcghQNyMgNfao2xdPU=,tag:u9mRQfCnceJVQ/qkHgyvAw==,type:str]
    QBITTORRENT_PASS: ENC[AES256_GCM,data:umWOqfVj3hDsfFEp+J1RE9FZ60hCsENhW77TpgvVS5U=,iv:ojIPyaGGQNpLvz7rBY+eg4WHfLlTfxpsjpW6dfjFoRM=,tag:dE3D+Jfr4CAMW+91AcnHLw==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSy9JZ3cxMlhtRjBTdkRk
            b1pWMHVvN2RDakUyV1JQVkUrelNXa0RCd3hFCnd2OTlPYkEzdEFUeE5QdE1BNFNU
            cDh3VG9iaTNBRndjdkt5R05UVllhaGsKLS0tIHFHcUN2NWl5akdjZDY2QVpIS2RL
            RXh5Uit6N0xEQzZ2cEpkVjgvWDBua2MKsmtK4ubvaMOItmtaOoe+AKr98Gx83JiA
            zC5opFH6B2MLnfkEMsaVlT0Ut3pcNxEBhPcjvt999quz1Q3O93sd9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T08:08:25Z"
    mac: ENC[AES256_GCM,data:7eB0pKN/9nsljeVfC9bvwC1XhlaOFPih8Y1QYRcfwpyn0AstGMBFWxQ2vHsXewMMNneGqDAouKTZMw6x8PXXMZmF8JbOwyyTfSTyxvcGVcFTjILgIE1opdcmr67BHsduZPddrPTq5r7Xu5op/VKSIj6C9oh1h553n8Tfebmoxf0=,iv:skvSSsiINPM0Lae3tN6VI1MU2BwnohTKHxXhDB9ZYlw=,tag:z8F+fdS0D7TZB0wE9nrw9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
---
apiVersion: ENC[AES256_GCM,data:AaM=,iv:pjUX5YpzmkbTTRS0n1rlqXkUNEeF7BqOR4mCvJWHPt4=,tag:SDdFqx5VRZfT0s1ECzZTvQ==,type:str]
kind: ENC[AES256_GCM,data:i3DG3cY4,iv:QjkVrDNQJy6KsBn2u/oX0wJI1AUXF+/8rCHWZVH8JJQ=,tag:axnS7xBdnYcBf6Q/UDNsDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fGj37EIB2wIv5lby,iv:TDYK5BtwGi8q3OJc5toINXGYZrumsnxkbdMSF4dRsSc=,tag:+75OnUz4hW2VW9PU/hd1Cw==,type:str]
    namespace: ENC[AES256_GCM,data:ugmv3iDznBM=,iv:s3ePc/XwDtmLkBGF1Vi26NUpkvz3QWaCBy2lHkeV850=,tag:zPox9899+cfVC0VEBAOU4w==,type:str]
type: ENC[AES256_GCM,data:wU9GPTRz,iv:8eUWRszjKGuH86UoUZsdpJPx/RbXBD64s8RXYFU5CW0=,tag:f2UvXd005jowH4XepW4rnw==,type:str]
stringData:
    config.toml: ENC[AES256_GCM,data:ElrnQMTJdIP/3g/qWK2OUvB+uOzCze3JJK4fOGSopINSVjnTQ7Z+YHrdwKM8OamiibdtCMEl0mOVeZuo1h1RDyhNmdz6i05DJgoB4tgzb6x4JD6gJZ7gDSF/4RZxkn/dxATovYjINSKGWahvU2OsqxWrF2Puk4vmb1HBB0aq5Fp+P+dmy+mo0I7/hokJ16X5mpB0BVgpUFfY0w==,iv:sAa7y3xE/2Gg5fGeKfjJHctSoo9PQKA6oSibxM1mouM=,tag:V2dl+eHp/913neQNVlfdYQ==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSy9JZ3cxMlhtRjBTdkRk
            b1pWMHVvN2RDakUyV1JQVkUrelNXa0RCd3hFCnd2OTlPYkEzdEFUeE5QdE1BNFNU
            cDh3VG9iaTNBRndjdkt5R05UVllhaGsKLS0tIHFHcUN2NWl5akdjZDY2QVpIS2RL
            RXh5Uit6N0xEQzZ2cEpkVjgvWDBua2MKsmtK4ubvaMOItmtaOoe+AKr98Gx83JiA
            zC5opFH6B2MLnfkEMsaVlT0Ut3pcNxEBhPcjvt999quz1Q3O93sd9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T08:08:25Z"
    mac: ENC[AES256_GCM,data:7eB0pKN/9nsljeVfC9bvwC1XhlaOFPih8Y1QYRcfwpyn0AstGMBFWxQ2vHsXewMMNneGqDAouKTZMw6x8PXXMZmF8JbOwyyTfSTyxvcGVcFTjILgIE1opdcmr67BHsduZPddrPTq5r7Xu5op/VKSIj6C9oh1h553n8Tfebmoxf0=,iv:skvSSsiINPM0Lae3tN6VI1MU2BwnohTKHxXhDB9ZYlw=,tag:z8F+fdS0D7TZB0wE9nrw9A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
