apiVersion: ENC[AES256_GCM,data:DkY=,iv:s0Z3iZkCwmQNTFW78nFzQ57yw4lcVlytvVlGNbsgpPo=,tag:/jE3LFmCyuKR+Q9DCDpWXQ==,type:str]
kind: ENC[AES256_GCM,data:5q4E4UTP,iv:16hKmbtvrJKfbDX/itKH6ddGe/8hEAlTI//Duqy/kqY=,tag:qgAzI4N+kgYZJeinfbVQ2g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mJ1sl1EmFXpwCNfrpsL8+X80,iv:zX9yq9om+DJlZRiUDjih9+gUyanc0sWidzdcvMqD5k4=,tag:GmMMA69tXMSxO6WITCPKfQ==,type:str]
    namespace: ENC[AES256_GCM,data:40jWWgHyVQ==,iv:lYDMGOFvOqGxQFFrsZqescd3kBhIuAbXK16NK3LSdnY=,tag:0ZT/Ay2HElfxDg2336i/bQ==,type:str]
type: ENC[AES256_GCM,data:ZsdPgZEV,iv:WdzvqKVBjIacOvAjJHtrDOgxJDEVG947hF5/xYSASxc=,tag:gnjBNGxdMYgwTptT8NO8iw==,type:str]
stringData:
    JWT_SECRET_KEY: ENC[AES256_GCM,data:2ZwnjybSUeaeFfwPamnj7NK9PnV9S37oPS6FqSdhVXs=,iv:cPsaKhyjZTTLhpVO+v/fXvVwQHCq2oIV4h28ashGOzo=,tag:47ZtOS7rwu7dVbePp/Cdxg==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:B5a5gprOdMp4t153stfkp+c=,iv:9CSDAvuR9nXaMvPdFW3N9DhkTb+8/+BQS9IDbmrgOJM=,tag:5P7xRc0d7kQZSccFMiwpIQ==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:aBepxVU507CTatwZWtW3eXThQBvUF3TdsiGkhQh6B3Y=,iv:os2KQoY6a0dPzJqpRNowSot3VZoM1NzRh0MNz3E+GP4=,tag:CDpWoio3dexUAkAr0mPexA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NDFqUTJYaTlENURuMTlk
            TFhOYlhKZlhXREJ0WlMxdTVtMVFGSzNxLzIwCkptYTVIYWJpZmdFMzg4dm1sZWRu
            VjE1cnR0T0pWemVrak1vVWFLZ0szN1EKLS0tIDE2SksreThpditFWjI5OG93Umly
            eTBManErcjg3WVhTUUZEaXNlOGRGS3MK/gB3l5TSuQ6UZjBVXTxVbLFma1WXQ4GU
            5ybiDkjRjn0j0Xv8Ubq3QVavGP8fvCpY5BCMRLtlP/bIQFRfzMjk9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:34:15Z"
    mac: ENC[AES256_GCM,data:ytXu56AadonHmTZMr2rs23xEdsjO2pcRG63TRJ78jkxSEPxAhA57jGtHurA5oF8roX6BU7u5CBDEChh8NP/oGpRomrDW1qURuU0WLk9d5PzQa7crNQry47BeJH6K+0LpKgPX8nPeu5hkksLFR76Z56SrtIut/eZG8UV1wYwJrBo=,iv:MBgCz8xnzw9rpIwHS6iuvyiw2+gU64qw9EU8+1rqUbA=,tag:zfw+e0wqhs3mSOSFW6agww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:P/g=,iv:fvPWut8pD/C+MJtv4W6oVval3LOfZJhel2KzL7xCtno=,tag:z+vv2GMAzHJUM/Zse+bINQ==,type:str]
kind: ENC[AES256_GCM,data:9wwLxhzg,iv:w2x+D1Xb/lOorJN4EDEJUWbOdJC2i5JtEkBy8dD98Ps=,tag:5HLzEyyoy0YfxGYW9Xme5g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VFQtgMUo7Tu9CGw04nRD9ikrrOGuyOno,iv:ca8ETJf913Ydy3c7Iasg1lSvwk5hOrS+f9JNANueTlo=,tag:p7YolSi/sQXHJBg5h/aW5A==,type:str]
    namespace: ENC[AES256_GCM,data:wT87/soGqw==,iv:L/k0TiSJS5ClBjSmB5iOjnnioukg1pkE21r6ALs8cW0=,tag:Dj6R8beNymaPkQfp1oabLg==,type:str]
type: ENC[AES256_GCM,data:SpSrYtnJTnd/7SOVbz863X6EQ9x3DDPk,iv:mefmXTv99QQCE0cp5ZsH+Yroty2EZYMpmGRhsricGEs=,tag:L2ObKBbyWVLfBv0Ry97WgA==,type:str]
stringData:
    username: ENC[AES256_GCM,data:rXTI4h83w2jXzw==,iv:6BTzE/tXQS6Zt4Sxe1XakIHPIoFMd5nM1MpuAKKZmHk=,tag:FshtOSZqMx0JhQyNx1o3YQ==,type:str]
    password: ENC[AES256_GCM,data:i5bi9aEep/exuqrNuxuIkR+ASAmCR8vrnCM+Zwp3VTM=,iv:gImo+q5YSm/Sy0NYhzpBIP5TmGZmWebn70SfUnM40EA=,tag:R/EyzonacyTW+ksh2cAOiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NDFqUTJYaTlENURuMTlk
            TFhOYlhKZlhXREJ0WlMxdTVtMVFGSzNxLzIwCkptYTVIYWJpZmdFMzg4dm1sZWRu
            VjE1cnR0T0pWemVrak1vVWFLZ0szN1EKLS0tIDE2SksreThpditFWjI5OG93Umly
            eTBManErcjg3WVhTUUZEaXNlOGRGS3MK/gB3l5TSuQ6UZjBVXTxVbLFma1WXQ4GU
            5ybiDkjRjn0j0Xv8Ubq3QVavGP8fvCpY5BCMRLtlP/bIQFRfzMjk9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:34:15Z"
    mac: ENC[AES256_GCM,data:ytXu56AadonHmTZMr2rs23xEdsjO2pcRG63TRJ78jkxSEPxAhA57jGtHurA5oF8roX6BU7u5CBDEChh8NP/oGpRomrDW1qURuU0WLk9d5PzQa7crNQry47BeJH6K+0LpKgPX8nPeu5hkksLFR76Z56SrtIut/eZG8UV1wYwJrBo=,iv:MBgCz8xnzw9rpIwHS6iuvyiw2+gU64qw9EU8+1rqUbA=,tag:zfw+e0wqhs3mSOSFW6agww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
