apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-replicated
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:vU04oHsLYrLnbeB94s4hrNxZSYb0uUz4kvEz1nkIhBVkjbe+Gy4avg3/1ki4GphCEbmgKquJLvoo/5EoOX4RSQpG72SJv9dtVb2kte25J6M86VcoGCbt+1oU67yLeCGIjJzF6mnTrBU=,iv:n/e6PCecCPKE18GKcRrvmmDNEnV7by+pL/0HNRRgVI4=,tag:F+gUYHbpMTKycGur+dTDEg==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:aYeBF+eCZ+/m/sAk8o2DdQH6WDJdasv+YfaSQw+L/gfskpznlhuUSu/XqgCEQEmieXljmQDhhXNFfq24T5q5KA==,iv:TzcpOhdelc7FNuXaEmlhD/cHVSxNiFCZLZFc82qEt3w=,tag:sfoR99LGJC8cVnxwPgr+IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVYzUUJBaDhnVFE2Snlj
            dmlOeVlpWnpkbzcwMzg3NHdVazVINm1oWTFFCi91UzlPRHpxcTlpOE1TejEwa1My
            TmlOeDdVcklMVTBCTmtsMUFqTG55OVkKLS0tIDBwdXMrQmpGMDN4d1dZRVQwQ2ds
            UllqQzdXU1BtQWZGYythSUlnTk9PWEUKrAXfRtAFyCFuvX/5DLD3HTjlCx5nrb5V
            chCJoCk0MccHUTKfTCAv+s+EOxBebE/fV6GR4JlukJLG8gTgeYBo0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:37:00Z"
    mac: ENC[AES256_GCM,data:X1Ina6L853lBzpeCpsfkp6pqLseTT0PZ7GlEFTa1tyuQQOyo40TkBPpNZumikrS2BR4Yo3RZuvUTpOnz31fwOms/gqZ7iovsxFvWGe9N2R/Q21Wao7kNDhK1/nZjo1bnlpzPH++UGoe+iLs/53aq/Ejn5pIUcCrqG2QK1yAltNo=,iv:PBLcqxsU2dMP47nBVJWSyq21v42/9zjK6mnSDiA85GU=,tag:hqGZ26ZkzLHb/QbQLVoccw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-scratch
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:CN5xfhAUSrqj3NDzdpfBDwUGW4VTFCM6V0O/UKtyPBZMEHAlGFv6rGxt5rth2c3RPLOD0uWgfIbCOOq56ik6/A92kUae8bDYeor2HhaG57obmv8ThyuFWQ4Wp1A+8s1+nbLPIRM=,iv:j8H4Mg+3QrTl6GiAwAxt69mXi6aYGATpMa3V/EkDnJ8=,tag:LswYstMDNPXzAGqbg2P0WA==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:X5CP3lh263j7c3fdYI6kHJNJAlvCs6BFZpbfo+ROF3200ifE0ozkb9Le8J44vYH03nnbuEnAs8afjtCxmBD60A==,iv:NakwOimz+RLPHNyE7gBNQAk5OzyYeZiVJUF7/yBuZ30=,tag:wTiZE6gYdETWgzPxmu1U0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVYzUUJBaDhnVFE2Snlj
            dmlOeVlpWnpkbzcwMzg3NHdVazVINm1oWTFFCi91UzlPRHpxcTlpOE1TejEwa1My
            TmlOeDdVcklMVTBCTmtsMUFqTG55OVkKLS0tIDBwdXMrQmpGMDN4d1dZRVQwQ2ds
            UllqQzdXU1BtQWZGYythSUlnTk9PWEUKrAXfRtAFyCFuvX/5DLD3HTjlCx5nrb5V
            chCJoCk0MccHUTKfTCAv+s+EOxBebE/fV6GR4JlukJLG8gTgeYBo0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:37:00Z"
    mac: ENC[AES256_GCM,data:X1Ina6L853lBzpeCpsfkp6pqLseTT0PZ7GlEFTa1tyuQQOyo40TkBPpNZumikrS2BR4Yo3RZuvUTpOnz31fwOms/gqZ7iovsxFvWGe9N2R/Q21Wao7kNDhK1/nZjo1bnlpzPH++UGoe+iLs/53aq/Ejn5pIUcCrqG2QK1yAltNo=,iv:PBLcqxsU2dMP47nBVJWSyq21v42/9zjK6mnSDiA85GU=,tag:hqGZ26ZkzLHb/QbQLVoccw==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
