apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-replicated
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:sCwZke1ho76icABjz2qJGN4LbpT/e7Huf0I1bmmuU+mywDXeZeJm1DHP76eKssb17bS6wHVsRJRLa/NYEoM3UvgnaWG2+SU364oAYTCnMLh0ZTwwo/3OenrmhU8l1uwL9jSkwDpQ7zkrkejZ5Cct,iv:x+jb9WE0B3Sb+Uec+2fWEp/za96GWwrT5C4NIaZ+zOQ=,tag:1wff/YoFuHkt0kzHoKjj1g==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:aYeBF+eCZ+/m/sAk8o2DdQH6WDJdasv+YfaSQw+L/gfskpznlhuUSu/XqgCEQEmieXljmQDhhXNFfq24T5q5KA==,iv:TzcpOhdelc7FNuXaEmlhD/cHVSxNiFCZLZFc82qEt3w=,tag:sfoR99LGJC8cVnxwPgr+IA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVYzUUJBaDhnVFE2Snlj
            dmlOeVlpWnpkbzcwMzg3NHdVazVINm1oWTFFCi91UzlPRHpxcTlpOE1TejEwa1My
            TmlOeDdVcklMVTBCTmtsMUFqTG55OVkKLS0tIDBwdXMrQmpGMDN4d1dZRVQwQ2ds
            UllqQzdXU1BtQWZGYythSUlnTk9PWEUKrAXfRtAFyCFuvX/5DLD3HTjlCx5nrb5V
            chCJoCk0MccHUTKfTCAv+s+EOxBebE/fV6GR4JlukJLG8gTgeYBo0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:09:58Z"
    mac: ENC[AES256_GCM,data:45XS1UX3LColjbpDvbbGyDwD9az5vaYFX3wDkY3LVtqgA3ZcqqunYxwOudQJGQ/cvP8Q2d/sW0hYh+cwAsRAkWa4mjPsdgs9jRc/gWzbQUexiM40aM6IDLG9p8etzA+HH5hqilPyIMpfQiWWnnsVhc7BlwXmL6T7Rm+1t1dq8Iw=,iv:wFH+kae/vQAell5T1Tg2sZ2PhviEILj52vglqMhT/v0=,tag:icEkLlu3kArChBleIWAKew==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-scratch
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:ttS0h8/9MIKXEsCZndFu7oo12S+CHjT3QiEkVSTtx9KiDt7cTt6Mdl8W3mPhB6pNQZdcuk3D2ioUTINet+IVcVcjM6yWvjiaSRcC0XC8Bn2CwdbFpsu4WYp3rfIC78yBbCa8Eun44N/WrTKM,iv:sCahU1Pjn/6oaIk1dhQ6ETdM3nJodu0jb+iIGTkYjGY=,tag:VuZoDSOt6wyPC4GkyX070A==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:X5CP3lh263j7c3fdYI6kHJNJAlvCs6BFZpbfo+ROF3200ifE0ozkb9Le8J44vYH03nnbuEnAs8afjtCxmBD60A==,iv:NakwOimz+RLPHNyE7gBNQAk5OzyYeZiVJUF7/yBuZ30=,tag:wTiZE6gYdETWgzPxmu1U0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTVYzUUJBaDhnVFE2Snlj
            dmlOeVlpWnpkbzcwMzg3NHdVazVINm1oWTFFCi91UzlPRHpxcTlpOE1TejEwa1My
            TmlOeDdVcklMVTBCTmtsMUFqTG55OVkKLS0tIDBwdXMrQmpGMDN4d1dZRVQwQ2ds
            UllqQzdXU1BtQWZGYythSUlnTk9PWEUKrAXfRtAFyCFuvX/5DLD3HTjlCx5nrb5V
            chCJoCk0MccHUTKfTCAv+s+EOxBebE/fV6GR4JlukJLG8gTgeYBo0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:09:58Z"
    mac: ENC[AES256_GCM,data:45XS1UX3LColjbpDvbbGyDwD9az5vaYFX3wDkY3LVtqgA3ZcqqunYxwOudQJGQ/cvP8Q2d/sW0hYh+cwAsRAkWa4mjPsdgs9jRc/gWzbQUexiM40aM6IDLG9p8etzA+HH5hqilPyIMpfQiWWnnsVhc7BlwXmL6T7Rm+1t1dq8Iw=,iv:wFH+kae/vQAell5T1Tg2sZ2PhviEILj52vglqMhT/v0=,tag:icEkLlu3kArChBleIWAKew==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
