apiVersion: ENC[AES256_GCM,data:1YM=,iv:G9XWpwCF7rlcZRGG7WEKSyYeUjJb7J6uxy4haYx8nwA=,tag:0cBL5ChKKWxu/u9VIfwdvQ==,type:str]
kind: ENC[AES256_GCM,data:tin98Fy0,iv:ruA5z9KaO9NZrOq1tpBZH2gxKaJMdmt+g/ZBb/ZpvrQ=,tag:DLg5ijNclTEneqokGnYncQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NjzEoNxct07F8g==,iv:1uq4s4w8EDYNIP6M+PIflmXe9JKnuq+OKJyA1Cay5pg=,tag:LLYJ2xww5G9bAb+aWZ0fzQ==,type:str]
    namespace: ENC[AES256_GCM,data:/cV74wgwow==,iv:msBlxCONmcXed8PhZ7O3HDxrFd3R3+0o1doQiS2jPOQ=,tag:d/e6jK2cQ685pZwwGz5NEA==,type:str]
type: ENC[AES256_GCM,data:uGcT7ZRH,iv:fL+wwdEigzcDGc8vNaeOodC0r0zgnkjMxPxz1M3krOA=,tag:fXe/1tUtCvlGAjWAreyS0Q==,type:str]
stringData:
    N8N_EMAIL_MODE: ENC[AES256_GCM,data:TmtRMg==,iv:gRiVtSX9HKla7G1kNVJO/4KG8934bHGwA4+k4v3kNSE=,tag:IlJx7zVt3gInZjE91rZorw==,type:str]
    N8N_SMTP_HOST: ENC[AES256_GCM,data:/DyBtunKDdGmbiwPUKg=,iv:4w4766wD1/+lvqHzi0f4wpJYwhWUCGKM//eKR8iA0S8=,tag:zmwftsWOzdHlINg54DD4og==,type:str]
    N8N_SMTP_PORT: ENC[AES256_GCM,data:LEmC,iv:ggXYkw2DW+j0fuQlDfL4bbH9RmqozI4ngpJpebPKC5s=,tag:3HnL8wS7Ri9mYRql2iOXvw==,type:str]
    N8N_SMTP_USER: ENC[AES256_GCM,data:wrT9XXvMXfy8WOUGSQc/I0o=,iv:EhTRwe4VJzABEs4XxHCwI1cl8LKUU+yBfPY5SDESm2w=,tag:g73i+6GlPaWmR4jyxlK3kg==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:U+UPEcwwMHq+Ac5UeMe5dWqQm+NIKnmfiiyLiaeYhRU=,iv:xRpE7OYbQkomlIz6S/iJjLKzI2gd9wh4864MsNEKte0=,tag:DYnuE/VoI2me+RnioEcLYA==,type:str]
    N8N_SMTP_SENDER: ENC[AES256_GCM,data:0EJsQ6+jdU3/fGNOmlKK2w==,iv:TuHGIk8wX69qekr8PUrF++vObpQXnx8XqRh23TEoJag=,tag:RrqLNBxy6tgCBTAcYOkaxg==,type:str]
    N8N_SMTP_SSL: ENC[AES256_GCM,data:ZsmcyQ==,iv:/lXDyweDUAu6sduXu+gLmJO0DE6KsYT2sRKwxSjtfHM=,tag:Hsl7LburLNuJnfjVdOR4aA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbGxTODVZUE1BYm56QVY3
            N0ZhaSs1QlIwZFRjNy80cDU3cnkwY3ZYYkI4CkFYNStlSzBBbmZCYlFwM3hKSU9H
            S01yeFhWQjJjZnZFKzZFTll1d0pOSEEKLS0tIEdGU1EvVTJMWnM1MkFBRlFad05w
            Y2FCTEh6NDQxVk9FQzQ0Y2ttQjlibVUK7yI/h7US15gCCgpPoUsOclczrCgMVKuI
            W1W8pQAaHntnJzMNUj+JbC6bgX4C2OLfHi31rpehA1deXi7fGxa9hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:35:27Z"
    mac: ENC[AES256_GCM,data:8FmTd1kjF00Hbb9OXAjHFR66hWfHjiaUMbPNb7eH845wfAAPx4gmSuT1Aj6sUUpf6LTknrCVnGj7Sa4UOhyPHS00ONHD4WUo7Oyod8YZUINMZ41/43oGDAI63XgrRmzXw/pel9wwSCJJfe81I4pFuaXwGYUjvMIgJzl8Te3lffE=,iv:Yu3Exhy/pqGKcAvIrESmdvsXHOgmaHVJXp1gzaoF8sM=,tag:HdLEMUeWq1Y27s8yh2ho0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:piQ=,iv:5aMuL0G2iYM9//SiLbxLj60VCjDeYxrT2mjb2gBA+YU=,tag:FyrhUltvrJHSl6n8uY+RKg==,type:str]
kind: ENC[AES256_GCM,data:Y393kGBj,iv:sAc8ptBJs7X5O8vQ9mmW/Nd2QtZG01bfhZukgYSKjIU=,tag:G/0HFOY/K7cewp3j9mYevw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Fq9CP3atRuKfejN/it3iAH8=,iv:xkKJeCJr+hB7l46ZqJcj/cHLtq3qdPZBCqlI34Hi6MI=,tag:Qhk2rxnlUlCzFCSqqQ3hQg==,type:str]
    namespace: ENC[AES256_GCM,data:UJDG9r1bNQ==,iv:daep25uluC6GJfPjj4g+lq9Fpwcf9UqxuXER5v2cZds=,tag://fw2SeZQOAHQ+vNZgZpPg==,type:str]
type: ENC[AES256_GCM,data:aGGOWhZ9u0fmgc4xMgCtz6MBV6v+2+yp,iv:7+g2NFX3lzAieJc9RfH/v4FBKPMU9BxMWYWoHGpuefA=,tag:RK9bwajXy883zkVpdF5Byw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:N7pd,iv:GdbJ7DauHuaBZ5i0RU919TrTGdlzFJdzJB+hn7sAejc=,tag:NIp/ST7eSjs3CLVuL/nS3Q==,type:str]
    password: ENC[AES256_GCM,data:xbpqgUkGj4nFpky7a/dc1fE7EXN3L66lzjgQTnGtNoM=,iv:Yy02oIV4IPPZXrV2BSSRtMA6biHqbam3kvbUpXeLYJg=,tag:rW32HCdRKIM9NeJW2CWaOg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbGxTODVZUE1BYm56QVY3
            N0ZhaSs1QlIwZFRjNy80cDU3cnkwY3ZYYkI4CkFYNStlSzBBbmZCYlFwM3hKSU9H
            S01yeFhWQjJjZnZFKzZFTll1d0pOSEEKLS0tIEdGU1EvVTJMWnM1MkFBRlFad05w
            Y2FCTEh6NDQxVk9FQzQ0Y2ttQjlibVUK7yI/h7US15gCCgpPoUsOclczrCgMVKuI
            W1W8pQAaHntnJzMNUj+JbC6bgX4C2OLfHi31rpehA1deXi7fGxa9hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:35:27Z"
    mac: ENC[AES256_GCM,data:8FmTd1kjF00Hbb9OXAjHFR66hWfHjiaUMbPNb7eH845wfAAPx4gmSuT1Aj6sUUpf6LTknrCVnGj7Sa4UOhyPHS00ONHD4WUo7Oyod8YZUINMZ41/43oGDAI63XgrRmzXw/pel9wwSCJJfe81I4pFuaXwGYUjvMIgJzl8Te3lffE=,iv:Yu3Exhy/pqGKcAvIrESmdvsXHOgmaHVJXp1gzaoF8sM=,tag:HdLEMUeWq1Y27s8yh2ho0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
