apiVersion: v1
kind: Secret
metadata:
    name: n8n-runners-auth
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2KXD3eXqjt/JytOXcuxWLp3bePI9v5NBL0/u5VUPWzWUe8wZ9ifH2wnihc1hT00GkBM5TsIUaMHOTPXkARfnCw==,iv:FXk4UDCA2fJhuIwRQB2+i7BSE4gL3payxzFzRMhL75k=,tag:cOMu3UybSaZFIaxVAefqzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNzhRL2lRZHJ3bitGK1Vo
            MmR5bzNNWVczbjVaUURBSnFZcWpRakRUL3gwCmFjcFUxYnZianVvL25pK2dqZlh3
            R0xUdXdoQm9WZTE5bkI2cWQrZG93MWMKLS0tIGllb0hDTEVSTW1PWU9PYXpRMVFY
            WXc3a1dmNkhKU1hwZVpLdUpneWQyUmMKCYgUB/8oQmYyetvIOgeoq5mxxe7dHFDH
            8aqHJRPAYv+oN/65NtlsYix+xBR1xezW5rFyfXIS49/1TFSrSgudIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-06T07:08:53Z"
    mac: ENC[AES256_GCM,data:WQVlQmNyBpoY2nShKatbuTVD7BTWHE9mK565bLfZThxcX8sG2bIKdEOghNZNv7fRGmBRSYoZK94BRy3r0XlI/QlSa2HBNJ2QI9Wgdrtj+SKOz1EOKOmsm4ie9+/2Md2kf2M6dHNBAIt//s+6LfoWQuAZO/6sDNcIy01pVgOdBPk=,iv:/mdhy5flQIIbEvsNMtAzOJ10i5KT0x/MUB6ea6GuyKY=,tag:Yw3lMnsHolOgcuKHPsR3/A==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.1
