apiVersion: ENC[AES256_GCM,data:6Vs=,iv:UVKGCvx8l+w+GTN//wpJJ96P5Nby5ZPqPDXZd8WruwE=,tag:Fa3r+cNPU0y3C6qiDFvazQ==,type:str]
kind: ENC[AES256_GCM,data:NGML5dUq,iv:+D4ebRuDU9u1dGIdzynb+4J6uRakQ3RtxcAFa7uDXjU=,tag:EeY+MyqP2LSRqgT7NuU4tg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:c3hgc9+cIEd3YorJXZ2t134=,iv:hGj4jZeSs80icezLb5nuPK9EI3w6m/qAbhbWMxPIdos=,tag:ip7gwgG8R/q846AoNocgDA==,type:str]
    namespace: ENC[AES256_GCM,data:4fQa7kggAw==,iv:eJ0Sh5awCM+B0Lrm2pQHxbF2hOvm0+QZMAWdcYPqPGs=,tag:6e1U88z6nMEFU2Ej5zIYGQ==,type:str]
type: ENC[AES256_GCM,data:nIVVGulc,iv:l7mLh7Ei9QG7WpEiQpRIuVGoYsdaZtrMCmAl7eWuAFk=,tag:AOAxWu+Ihfg3QrSe+ndcFg==,type:str]
stringData:
    smtp-username: ENC[AES256_GCM,data:crf0d3XnERkudyom1JvGoRM=,iv:NVpSrss5n3CJ7D/tE9UHqbNjy/q7J6p+BVQ7UQiJx+I=,tag:ItJMfXr5RSSe7JWMxCNNFQ==,type:str]
    smtp-password: ENC[AES256_GCM,data:fhFVvWkhb8PCdpPe0OV4hySzmSjIIbMZ31Hwm5tz4rw=,iv:nQRPWj7gmfGXtOJRqLUlLp95jl4RH+tt8XUG47SZMZA=,tag:Et/jkZYKU7ZMQbRRLGEqcg==,type:str]
    smtp-host: ENC[AES256_GCM,data:rIHva8z7TWOfHxevAs8=,iv:dAcp7PLWVI2vuZIDcDIphcJYiRmPoKh6zvxWaxyN/PY=,tag:m91ToUqYfOfw06f/vVZkAQ==,type:str]
    redis-password: ENC[AES256_GCM,data:uBV4CLK2FDy1nVua63lnVviZKkiqEfmA+Tqrp12NvhM=,iv:0CzvN7xTfuCBwREbmMGu6PtuG8TiZexqd9KhQ/Ssmi0=,tag:6rIvcHGKLadgl/Ju40/uWg==,type:str]
    nextcloud-username: ""
    nextcloud-password: ""
    metrics-token: ENC[AES256_GCM,data:EWh0JMU+ekSM3JE+yxwlUMUC+3im9W+zvWgrA8xPrJM6kdgqVXX8WwwS6aV7Q8Erd77CMcpJ4UTGPhvFgUMFPg==,iv:fwvbmYxBAc0y8XeubxAxSAdmozrtThXXsrELC9FPMAk=,tag:CjPvdl0bTxNniKLHOrIs+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFEySmN5b2ZReWJSd2hp
            M0FKZmQzY1d1S3dBWTZBWFIzVFJnNzdUeXlNCjlPODJla1lnL0VGTmhHb2c5dHlx
            enBPN2xvL1N2MEtRdDJWMUw0SGxjQjQKLS0tIGJnSUlCUHhEblpDbTBCdTdxOC9N
            Z3FUQkwxQm9DdEtUZDIvT0ZYOWtxNXcKW1Yq+tPUgZtXMN88cFTmmUOD853H//N6
            TB4wja2YX+/ZO+CwjDMFB4z9kTdZDRUDHO7n7JVdtSsxeFOs7lGgpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:30:45Z"
    mac: ENC[AES256_GCM,data:dt75p8fPBxrGjYgiX6f38wo9ELCL4FF8nLCLk7Xg454g7WS/Im1QMvpfd/UtZkJ38TX36nIGaLwNyeckeJeQgA2ZZ3of/YF9fmu+5pyMyH5txmTSysAwYK0tLUtyog1zYsEbCfTS7u5F+s8rPx6s4d7a91/PytwsYggUvI1t1MI=,iv:+1AnLAthcex3MoZpZB4IfCQlcdLR64buB0dZI7tRzz0=,tag:w2FKhUhpP2jx/BT+ody+4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:to4=,iv:tuO0g5rAuRCwbbsmUrnWl7ifC2mzDjC1dIZ1B0gbkIw=,tag:6bJh0w62AtdyFjis2TIm/Q==,type:str]
kind: ENC[AES256_GCM,data:P+zr3TAk,iv:MapJCrhfK9NFRxQPdcpzMP5pZvO4dn4dVoW0zNKF2SI=,tag:j0svv+4fCRFl+5waVxVi5A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:YZsMf+G8st+2LjfhBpGfX9+k0NMsaL4=,iv:CDlKqUjTPJ61b80gIKq912WPT4pQ2Hj2diPwdWIFuM0=,tag:7VcdIAWAUkMlHjp9hw6H6g==,type:str]
    namespace: ENC[AES256_GCM,data:9QbEw4maDw==,iv:NVtKJd8TbJ1Q0Xxj2phRvaUBn4p2kgllivyUzMDuQRo=,tag:VozcdkgnoM/OP0djKYAuBg==,type:str]
type: ENC[AES256_GCM,data:vFPPLy43JVHQjJ5K55n2ufnBgrpz/KAs,iv:8zp+dnzIYjt606FCnME1ncKddZNUC4lG8V5ct5HZQSc=,tag:vrpyAXqrRjVuzvrlPRAA0w==,type:str]
stringData:
    username: ENC[AES256_GCM,data:AoQhkRk3I8XG,iv:77rrkWWJ9ubNF6WduYyxzspgXTbEhvYrQ3gzbeVssAs=,tag:Bu5pC0taT6O7+xpCLo74tg==,type:str]
    password: ENC[AES256_GCM,data:unFe5i92bdfcUzCC5QCC1w3fLVaNs58PRC3P9X6EFXQ=,iv:fGYQaDDWkEw0S3h6OJ85TaoFJ1K7X7iDFUGquBJYAKY=,tag:c2UqAZWx24z/A8IvedU33Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFEySmN5b2ZReWJSd2hp
            M0FKZmQzY1d1S3dBWTZBWFIzVFJnNzdUeXlNCjlPODJla1lnL0VGTmhHb2c5dHlx
            enBPN2xvL1N2MEtRdDJWMUw0SGxjQjQKLS0tIGJnSUlCUHhEblpDbTBCdTdxOC9N
            Z3FUQkwxQm9DdEtUZDIvT0ZYOWtxNXcKW1Yq+tPUgZtXMN88cFTmmUOD853H//N6
            TB4wja2YX+/ZO+CwjDMFB4z9kTdZDRUDHO7n7JVdtSsxeFOs7lGgpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:30:45Z"
    mac: ENC[AES256_GCM,data:dt75p8fPBxrGjYgiX6f38wo9ELCL4FF8nLCLk7Xg454g7WS/Im1QMvpfd/UtZkJ38TX36nIGaLwNyeckeJeQgA2ZZ3of/YF9fmu+5pyMyH5txmTSysAwYK0tLUtyog1zYsEbCfTS7u5F+s8rPx6s4d7a91/PytwsYggUvI1t1MI=,iv:+1AnLAthcex3MoZpZB4IfCQlcdLR64buB0dZI7tRzz0=,tag:w2FKhUhpP2jx/BT+ody+4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:FFA=,iv:kVi2NS+7/Px4Q1WPKVpHSKKllc2eJXMSZh8133LIe6E=,tag:3RFoMnD4j8MUcOrtE7rezg==,type:str]
kind: ENC[AES256_GCM,data:WAFFVnjH,iv:aMNW5AcMSLrirfqON7JtDak10jfAKkzink8fvKUOzEM=,tag:RjkFklrB9U7pVTaB0ud7kA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hHSGb22gK+Mx7CQKbbE=,iv:rCv1K52JGUcvI3w2KD4lWcfZDwaHp1/VYRV5JfcFGv0=,tag:/8LqBgUHlaXAnlDkiTGQNg==,type:str]
    namespace: ENC[AES256_GCM,data:sDJKzh+rnQ==,iv:d3YmEKq8301Q0wUElyNL0isCCOQNwie6g8HUcCPo6Gg=,tag:0wKAG8LfdifvdWY9hr0jGQ==,type:str]
type: ENC[AES256_GCM,data:QE6RVF3d,iv:xXuBPLphOeJeGBFzSw3OoFFhyTb35s8u4itRk6qMMwk=,tag:/RDvCPMu0475ofS855pXzA==,type:str]
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:mRj/UN4AJL1QWg39hH7h9WBV3aremg9oBZC2wU78iWpQZ6bCz45PpKBLutZ7g+xq8RitrJbaVmdRnvmQoq64tc23KXhMbvIfV9TrJDxDV6DWOPX8poaWjSRlXxXSnffm,iv:P/Ke5mCholcBEDaY8sj70PGfAPkBJfb1+GaQvXF1iUo=,tag:A+uaMcqK5iQlMq6x+3TnyQ==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:qaGe3MKaZ/+EhHyaUDEHvxGJZEf5tEfZ3t622ogcELhc7U068d2UtzxVCPk0pN9rHjMtqRZcpPk5pcxZpgnkZQ==,iv:XLRYS7vq6O5OjuytbIb5lKnlM33yOBvJibIACdGHTNg=,tag:GmKwtsq2DixQ/ichR6xDmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMFEySmN5b2ZReWJSd2hp
            M0FKZmQzY1d1S3dBWTZBWFIzVFJnNzdUeXlNCjlPODJla1lnL0VGTmhHb2c5dHlx
            enBPN2xvL1N2MEtRdDJWMUw0SGxjQjQKLS0tIGJnSUlCUHhEblpDbTBCdTdxOC9N
            Z3FUQkwxQm9DdEtUZDIvT0ZYOWtxNXcKW1Yq+tPUgZtXMN88cFTmmUOD853H//N6
            TB4wja2YX+/ZO+CwjDMFB4z9kTdZDRUDHO7n7JVdtSsxeFOs7lGgpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T08:30:45Z"
    mac: ENC[AES256_GCM,data:dt75p8fPBxrGjYgiX6f38wo9ELCL4FF8nLCLk7Xg454g7WS/Im1QMvpfd/UtZkJ38TX36nIGaLwNyeckeJeQgA2ZZ3of/YF9fmu+5pyMyH5txmTSysAwYK0tLUtyog1zYsEbCfTS7u5F+s8rPx6s4d7a91/PytwsYggUvI1t1MI=,iv:+1AnLAthcex3MoZpZB4IfCQlcdLR64buB0dZI7tRzz0=,tag:w2FKhUhpP2jx/BT+ody+4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
