apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: default
type: Opaque
stringData:
    paperless-secret-key: ENC[AES256_GCM,data:kP7tIJCMI8/LJQj7AHyXTIJkoaFhmxI6DYJsSuFQUIc=,iv:ZgyfzqaFD0Vt0jujOjzgnVJYKmivlQdwurzHOuuTxTA=,tag:TPm/OL5jsPjXXsOJedDE+w==,type:str]
    healthcheckUrl: ENC[AES256_GCM,data:pTVg2jtRI9KDi/TWoWV0a3KBU/UspOY7WhHoXDhz5Z/S6fsqTvo7OC/w0VcUpgZYP0r2c4Y3AFI9BWBgY6fTQkYr1iZaUpS8oOJJX0/zhy47y/11lvGtjy2pqOJLw21RRP15kHmauw==,iv:+JGt4hgCgwkuhr8v60w2dZ9cEjtSZ8FqaSWIYHOLllw=,tag:dVwa8nYeFZPUz/+lolneUQ==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:mPa1lDc085HcsraBTrMqGq8BDNHn2ers/cbyCatesqARmRGkwu86vZ5lmBRitPUX1ditXIhDEXwWn0aW4ilNMA==,iv:sx8jKl88p0J8iRLfdo5KSaryaDx0xUg0Ig1kt4QF3II=,tag:cX7hTING2Y0F68dgxRHYxw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTmlaT2pRSU5DYSszWkFT
            U0xNdGhJU3RYZFNObWdBNGV1UWpDblBXclYwCm5weUkrVE9lREtBK1I1bnoyTlpT
            ajdJa3pUc1ZqbnNYV0JxdzQwcXJqRzQKLS0tIFA4NW9xMTN2ZnVBVDdFaHE5ZzRh
            MW1janhVZS9LejYwU0JmbzA5S3J2TkkKZv++4eOwL5S7u5VTy7nTyJ8T6+CmQcZi
            67T76EVvIAYl++JpMFRhbUROa91Fs5W+MQ16+hyNIXezeIdA6+4Baw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-08-29T08:46:32Z"
    mac: ENC[AES256_GCM,data:a6QGVGhsJ/4VN/8jOfVkbzz03N2IYTpSNA1kZX+3Fyvn1u2lIHQYm7zhB20wS0xs07uYLdGAnhf/7gjHqTCH4lAszDO6BQGgdiTNmg3tbvEwKtOG0XldTIKIS/J0G3oVL2TCicYgEGu10kiNMSIazfNljzOaMeW/MF3+8bRvyco=,iv:/sLZeZKuAlIM0dsBciML59vzB6FLl9JEcPK6vw61pvA=,tag:Tgjf0gesLRK43S31gDIimg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: paperless-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:LaT49suG8s0pW2iqEA==,iv:BDtOhmI+SOkDlNDKB6MmPiF0wj76GU1Lf3kOWa17xz0=,tag:GguWa/bRDSRJvRGdKTY6fg==,type:str]
    password: ENC[AES256_GCM,data:UYmNblgjaxHeIUF6KyyeQHOuSi1Go1ngdosU0wDAdjk=,iv:NFXpv/76XixY3xW1mODC7ifpqk42KbszW96L2wJ8kio=,tag:NN/0Q9OifdNJoVaNbK1WmA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTmlaT2pRSU5DYSszWkFT
            U0xNdGhJU3RYZFNObWdBNGV1UWpDblBXclYwCm5weUkrVE9lREtBK1I1bnoyTlpT
            ajdJa3pUc1ZqbnNYV0JxdzQwcXJqRzQKLS0tIFA4NW9xMTN2ZnVBVDdFaHE5ZzRh
            MW1janhVZS9LejYwU0JmbzA5S3J2TkkKZv++4eOwL5S7u5VTy7nTyJ8T6+CmQcZi
            67T76EVvIAYl++JpMFRhbUROa91Fs5W+MQ16+hyNIXezeIdA6+4Baw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-08-29T08:46:32Z"
    mac: ENC[AES256_GCM,data:a6QGVGhsJ/4VN/8jOfVkbzz03N2IYTpSNA1kZX+3Fyvn1u2lIHQYm7zhB20wS0xs07uYLdGAnhf/7gjHqTCH4lAszDO6BQGgdiTNmg3tbvEwKtOG0XldTIKIS/J0G3oVL2TCicYgEGu10kiNMSIazfNljzOaMeW/MF3+8bRvyco=,iv:/sLZeZKuAlIM0dsBciML59vzB6FLl9JEcPK6vw61pvA=,tag:Tgjf0gesLRK43S31gDIimg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
