apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-rwx
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:EXv4e6TQEzkfweUYh8HNXl03Jr0ggAKMv4q2j8pps22gz+GEv1GPU15Rs4PolIlWOAXcHx6RX0JwwOXp+3km6Jk+GMyIRbWm9zdikKqPNRhQJmyB08c/zZpDVjupwt0Z0A==,iv:HMNM+jpIs2ONvwZUqHfr9Se1LY6Jn26JyOkpsvZIL6Y=,tag:/DhKvl05J96t+qVVJ+nDiA==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:ay9/Q4HOwFhB59iCYDEkBgvKU6yu3+u2BUNw0FbC6QwTuccv0LMZNFwQ0m60BKcWDvbhLnnSJxqpTx7Ip3FWFQ==,iv:2NSBscPyBCLbVegZa4N3cnPnJIKpv/9uzO1ghs2+tAU=,tag:co5Qy6rQZTR9mU78BoKByA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZWg0V09mYUU1c24yWjdD
            ZmNZVlZRN2U0Q25LTWplSzZkYVgrT09DdTJvCnVnZ1ZPZVNaODdIRE1zbHQ4b2RV
            dktCS09La1VZdk5mZkM4KzB1WFVISjQKLS0tIHUzcTBHWGFRNXRteEQ5VjRub1BU
            QzZ3RjBsUmlQS2Y4bXgyTlYwdEYwRG8KHO9FdSHDs++wfuz2FqE1lNnPasNt9N1h
            cXEtDwnUMipUfuq46NCdUAewmIHztSr3JUtkbfXkmhUneRYAE4ET5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:47:33Z"
    mac: ENC[AES256_GCM,data:AqbHTF2Sb6a7QmFNvMqFy59s5UcubTBh0DGF89kNBhKAzyY2u2mLofthnNauQwdNByr2fhVqEX1doPMlA5ml981hbPsl/kxoJVrJwgTxcZsB7FUH86Ui0P5sn2Cmx1B/hFwhGzHQ5JP3+uHsboox4hfC47Wli5tcHURH3DvklhE=,iv:EnhfXWW4Ca/Wh4JFKShXwG+u0pKdbV4uewIJTnjJI6I=,tag:VohXLsjC2RSMN9QGPMD1Qg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: longhorn-canary-handoff
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:igX/OqRoGGOtkwfTSgyimHKMVtJih7L1cTgQAvUPNgwTYcqrgR3EflDoeEIzTcKDpwtSyHUluuMp6W9WV2feGfeX6f18DQF1pj3M7fgTmk7fwgo91gWbnDdWBGBS+8IN0WDeIX4=,iv:0qJeKYE253OWWTDhNG1lBFh3xJ/1oAqARSBL5bREk10=,tag:m/EHm/9+1/8+jPBdpuHvWQ==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:WViW/gtC4GdDxpMUpy0Qcq8Nd96f8NWJ+DxC/I97BtjEuPkC3bvkKHrbAI9NYlqYMzs4X5EGei8u2DNSfIoffQ==,iv:H28Bazdjeqh9wpoO9DNGbr5FgUN7PmNWNSLprLVIuP4=,tag:hBSvUSIEjyLDHPUg1+D8Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZWg0V09mYUU1c24yWjdD
            ZmNZVlZRN2U0Q25LTWplSzZkYVgrT09DdTJvCnVnZ1ZPZVNaODdIRE1zbHQ4b2RV
            dktCS09La1VZdk5mZkM4KzB1WFVISjQKLS0tIHUzcTBHWGFRNXRteEQ5VjRub1BU
            QzZ3RjBsUmlQS2Y4bXgyTlYwdEYwRG8KHO9FdSHDs++wfuz2FqE1lNnPasNt9N1h
            cXEtDwnUMipUfuq46NCdUAewmIHztSr3JUtkbfXkmhUneRYAE4ET5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:47:33Z"
    mac: ENC[AES256_GCM,data:AqbHTF2Sb6a7QmFNvMqFy59s5UcubTBh0DGF89kNBhKAzyY2u2mLofthnNauQwdNByr2fhVqEX1doPMlA5ml981hbPsl/kxoJVrJwgTxcZsB7FUH86Ui0P5sn2Cmx1B/hFwhGzHQ5JP3+uHsboox4hfC47Wli5tcHURH3DvklhE=,iv:EnhfXWW4Ca/Wh4JFKShXwG+u0pKdbV4uewIJTnjJI6I=,tag:VohXLsjC2RSMN9QGPMD1Qg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: nas-canary-replicated
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:KukI5uqUp3OgMfqxRQ0yadHvmcozJJJi18L2djHRYLN3vS6JmS+EzRdIgSrQTvx8JufSdhsR6yMlV3W5GujnKMXYxfysdyjEUlC3Ybqs5bfczNv4O1EF0U+Q4F7vnwtqAQEJ,iv:foBb1WwKYhH33WmMZR61YP4YAKkJSWzq5qiyVT0Rm6c=,tag:x+oLLGY8p/t0w6G+G3dotg==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:d/2bcIRqlWwL/wOjyfgnCJNdHMJgdhEv98GcILOkWVubdSu5joyk1dGKU8oL77Ht9yYm62ZZklqvOsTAFahc3w==,iv:i2vDuz6BhactYme41kBGRtlIgKzk0DLeEx3wDavkJHc=,tag:QEyszHwj3H2sqqJvC/7KiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZWg0V09mYUU1c24yWjdD
            ZmNZVlZRN2U0Q25LTWplSzZkYVgrT09DdTJvCnVnZ1ZPZVNaODdIRE1zbHQ4b2RV
            dktCS09La1VZdk5mZkM4KzB1WFVISjQKLS0tIHUzcTBHWGFRNXRteEQ5VjRub1BU
            QzZ3RjBsUmlQS2Y4bXgyTlYwdEYwRG8KHO9FdSHDs++wfuz2FqE1lNnPasNt9N1h
            cXEtDwnUMipUfuq46NCdUAewmIHztSr3JUtkbfXkmhUneRYAE4ET5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:47:33Z"
    mac: ENC[AES256_GCM,data:AqbHTF2Sb6a7QmFNvMqFy59s5UcubTBh0DGF89kNBhKAzyY2u2mLofthnNauQwdNByr2fhVqEX1doPMlA5ml981hbPsl/kxoJVrJwgTxcZsB7FUH86Ui0P5sn2Cmx1B/hFwhGzHQ5JP3+uHsboox4hfC47Wli5tcHURH3DvklhE=,iv:EnhfXWW4Ca/Wh4JFKShXwG+u0pKdbV4uewIJTnjJI6I=,tag:VohXLsjC2RSMN9QGPMD1Qg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: nas-canary-scratch
    namespace: default
type: Opaque
stringData:
    healthcheckUrl: ENC[AES256_GCM,data:gBlYfbR5HjbcnKoQZxot7cmq8HAAPISXVUlcRMKWb2icower36kewnbnu+WAB5/+f4XEYJy7a++YDDMcRRTv0sk/1zbt+AtKBlG/tdkfBkIu5PgYySl8dm0t/v4Uc5bR,iv:tL8HaQlBAa/RYmTlKvyJoaDv7Rky5xqfNrazhz3rX6I=,tag:2pQAfmCCcAbeqkAYSz680g==,type:str]
    healthcheckToken: ENC[AES256_GCM,data:/bVhGwM44xsoKo2C4QTN7OM4/Yvetx8trduKugaV3Cjfi81ei76B+wOGNGmyzXmnd33mOxnohfRwFHtpnzVUFQ==,iv:BQ7MWmcI9x1IT6I4DUX3f9NaxZMr/nUHFbISXHq6Hpo=,tag:vKnoNSsvqK6j73aLt8a52w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZWg0V09mYUU1c24yWjdD
            ZmNZVlZRN2U0Q25LTWplSzZkYVgrT09DdTJvCnVnZ1ZPZVNaODdIRE1zbHQ4b2RV
            dktCS09La1VZdk5mZkM4KzB1WFVISjQKLS0tIHUzcTBHWGFRNXRteEQ5VjRub1BU
            QzZ3RjBsUmlQS2Y4bXgyTlYwdEYwRG8KHO9FdSHDs++wfuz2FqE1lNnPasNt9N1h
            cXEtDwnUMipUfuq46NCdUAewmIHztSr3JUtkbfXkmhUneRYAE4ET5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-10-10T14:47:33Z"
    mac: ENC[AES256_GCM,data:AqbHTF2Sb6a7QmFNvMqFy59s5UcubTBh0DGF89kNBhKAzyY2u2mLofthnNauQwdNByr2fhVqEX1doPMlA5ml981hbPsl/kxoJVrJwgTxcZsB7FUH86Ui0P5sn2Cmx1B/hFwhGzHQ5JP3+uHsboox4hfC47Wli5tcHURH3DvklhE=,iv:EnhfXWW4Ca/Wh4JFKShXwG+u0pKdbV4uewIJTnjJI6I=,tag:VohXLsjC2RSMN9QGPMD1Qg==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.3
