apiVersion: v1
kind: Secret
metadata:
    name: wger-secrets
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:SS4J9aBeKCROEdb0SahPSSO1mo2+T6Oj7YHG0wNxy3newJfsEo/n9sh7Orv7T8DH7+8=,iv:0ThMXE7qMrLzbgNbcZXtCYw+ZX6NNY7jOUIhD8jCzoU=,tag:cE5ZH3zB6VBzJV/R66/KcA==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:VsJjpAHR4yNcNswW0KePegQM63EpJ9HgR9LrHkdsaPp/dh0Hxw0TJNB5uOsEyGIYXlY=,iv:NBsZB9Mh7ZLyUf6wywkUapar0gM24tZ0Pd7kfmIynPw=,tag:swd1pp7NDTCjC48Dy7mmjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1Q0US9NMkRETUNuOTR2
            c3NtS3JqU3lsWkFDVTJDa0cyQlZTYXJVMzFzCnR5UkRXbi84UnVjekNWMUlHbVlm
            OTlYZkJjSXladktFN0hKNlMyZHltV2sKLS0tIEUrSkMrWkZFSFVFc0RWQXozaDl2
            MTAwcVNhNXoydGorU2lsMURqaUxlZk0KpFhzUt2aSD9AKP39Hr5BToimtgA5Msvy
            EPFPTHvJLeS3R9irNeKDrLTr3LDgHQX5Z6SA7liv7CNFAVDFRhEByQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-02T19:45:18Z"
    mac: ENC[AES256_GCM,data:6MDIPD3bNFwG311g0YW64mH0+tFmxSnk4peVnuxqsGsuPretHzsqpgpMaw3BkIYnbaVUTZ+PvC+u49fkNV4hYEFRE70ByCsuV/2UlQ+U/30imeyOyNYT4iQPStcUHo0nNudrw9kQrDe2phvHea6J1wpVugNgIlxl0jtD+ZMYg9Q=,iv:A3gWUthtrBdOEpFIPfN6QY34+BmcIxoukCH/K9pqpok=,tag:p5P2tqLV76vtS1WXRr1+DA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: wger-postgres-user
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:DLg2sA==,iv:cL0YCq11xCxTwoXN/tS+F0j7IHESpiK8c1OQW9pqlYw=,tag:mbkpGFeRXr0RNIWGfgAgcw==,type:str]
    password: ENC[AES256_GCM,data:7S3cV9Ur177/ho2mppecvaFlvylHjR3AFgP+1bb4Zw==,iv:LVOTLV2WrQomsou4j5DMaNBcbOwx4haE6qW7KwfV4Zk=,tag:aHqzVbm7WWJL9OuhWHVNAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJa1Q0US9NMkRETUNuOTR2
            c3NtS3JqU3lsWkFDVTJDa0cyQlZTYXJVMzFzCnR5UkRXbi84UnVjekNWMUlHbVlm
            OTlYZkJjSXladktFN0hKNlMyZHltV2sKLS0tIEUrSkMrWkZFSFVFc0RWQXozaDl2
            MTAwcVNhNXoydGorU2lsMURqaUxlZk0KpFhzUt2aSD9AKP39Hr5BToimtgA5Msvy
            EPFPTHvJLeS3R9irNeKDrLTr3LDgHQX5Z6SA7liv7CNFAVDFRhEByQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-02T19:45:18Z"
    mac: ENC[AES256_GCM,data:6MDIPD3bNFwG311g0YW64mH0+tFmxSnk4peVnuxqsGsuPretHzsqpgpMaw3BkIYnbaVUTZ+PvC+u49fkNV4hYEFRE70ByCsuV/2UlQ+U/30imeyOyNYT4iQPStcUHo0nNudrw9kQrDe2phvHea6J1wpVugNgIlxl0jtD+ZMYg9Q=,iv:A3gWUthtrBdOEpFIPfN6QY34+BmcIxoukCH/K9pqpok=,tag:p5P2tqLV76vtS1WXRr1+DA==,type:str]
    unencrypted_regex: ^(apiVersion|kind|metadata|type)$
    version: 3.13.1
