apiVersion: ENC[AES256_GCM,data:7Jc=,iv:ck8irkW8pfSAiAbScJQsgR+2+St3iLIFgD8qCRuQuWQ=,tag:BoCbGmETEI+PXNf7wpKHcQ==,type:str]
kind: ENC[AES256_GCM,data:6ff0AUOj,iv:37S++VyjITBnMK288yi2kMq2RD0CH9sB/AR5vN8kMAU=,tag:n17nRqbucxPEQzx0QG10bw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kREqcj0hXrJwO9zq,iv:6L9PQ+eP0modKEA61z+8IB0zXrsGXOxwrLnXXeKTFlo=,tag:GHQtB5J4mHwrgMfEg16SeA==,type:str]
    namespace: ENC[AES256_GCM,data:6ew+70yiCQ==,iv:twde01pbOtcXtQhkugz1ngK9LkVmQlyBzGl6aFD8JOk=,tag:BjMZW9vYJGoq06mjVW7Xsg==,type:str]
type: ENC[AES256_GCM,data:P9YpIrKV,iv:HOR79NvsAoGTbocdtXdmj3N8KL8bmf8xU5KnDwFLDUo=,tag:emshaikNjGYjGblI8a6l6Q==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:kQOnEVZsXL+N2dVErBWT7WJkPcprK5jOUNQ5ZgOOENPfadGosOvFkUUHOSL+DVSh+cc=,iv:KyptYRdFF7XyjmNKxaElbBvFY7iQ/1ThJmHmuESJ/VQ=,tag:zYyFQDTPqr+CRDwMfzaaug==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:pU8QRj8/D7fctmTh7HV0XmT7G2aUEN1X/5M6pYPtA6LbQycqDkwsAdOtxNTSYNGkx+Y=,iv:FtoFwHCjkfAlJSS4ZBcWflCqkeemP4zfCx7tEy2bz0w=,tag:Hjje1lWnJUcGz7glyY3kLg==,type:str]
    smtp-username: ENC[AES256_GCM,data:0ekTBlIuxn5cH8ktSxcsyv8=,iv:CtmSxUXUs+gAAO8PsqT1vN2JbovemcJ7RFI0Hracvq4=,tag:k9J+DUESEthBzKnEG5m4kw==,type:str]
    smtp-password: ENC[AES256_GCM,data:F+Yk8fTPt8X/1VWoAK4TUjblDxLYQQkPvQ4snNzOEyU=,iv:s5WcJCTNyFqEtOTo30GG3Zls5qtgp7tlXJ638coH9gw=,tag:PVNzLVKudpGY2yuTdJd69w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcmFBY09iRGRWQlpIWW11
            alZ0Q0xuZmtDVFhoNDZsMXZTbUk1R1JIL1VJCmRhRnphdmw0bko4VURCZlNGWVRo
            ZmZlNjA3MmRuY2g5Qy9PNHJYbk4wNlEKLS0tIEh2YjVUKzk0T1FrWmdRbU1kckhD
            Mzk1NWtkMk13N1pEUkQyMVZWbDg5emMKCueQB3bM/IEXXJET3CwtBmk7auiVChGo
            PTCd0it6iPelVESL0XcWuLJnlRK8rpRy569f19EMGPypRgOTRDMsTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T09:37:03Z"
    mac: ENC[AES256_GCM,data:VogCO2eGxBc/sDtLLsYYMSCP35/KG6r42LosPfPbogKnNByhsRV1JrUSG9TRp8Cp71L8FY8SV10QCUyHgy4tUWW4GsWuv/pENogurKDOBvjElB5EKEB3n4sO4TaST0hLtDJSCw8X1iV9gmWO2h+gM4vy4VOffrzRBcHUaY4raJI=,iv:+sCS3aotYxUqq3HYltR+VMEea2xnjMWcApI18RmDkvU=,tag:3APD52XNslmwDrECT8ya8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
---
apiVersion: ENC[AES256_GCM,data:7Jc=,iv:ck8irkW8pfSAiAbScJQsgR+2+St3iLIFgD8qCRuQuWQ=,tag:BoCbGmETEI+PXNf7wpKHcQ==,type:str]
kind: ENC[AES256_GCM,data:6ff0AUOj,iv:37S++VyjITBnMK288yi2kMq2RD0CH9sB/AR5vN8kMAU=,tag:n17nRqbucxPEQzx0QG10bw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y8e+QhyL5++moIRSczjNRi8+,iv:b40AxjmTIWFoqMHtMx4RzpWL8IipTwV5b63KJRoSH64=,tag:6KtcFurchzg/0lQYxQvFuQ==,type:str]
    namespace: ENC[AES256_GCM,data:6ew+70yiCQ==,iv:twde01pbOtcXtQhkugz1ngK9LkVmQlyBzGl6aFD8JOk=,tag:BjMZW9vYJGoq06mjVW7Xsg==,type:str]
type: ENC[AES256_GCM,data:jSYcUTA/O1mGjQaPOqScAeaBZMygNsKC,iv:B+RtHqMO//n5B/SJWbKS81/fm4sYvso1F3G+x+14ktw=,tag:rSBzmHL7tjDsnkq2udMgtQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:L7JaCg==,iv:d26HSThjL8cZd1SF2hPyqevdunHhyUdOMXdpCyUd86c=,tag:5Ih8mgu/A5H76dgwva5OYw==,type:str]
    password: ENC[AES256_GCM,data:VPRgelCdNzdTc3dO6I8ZP/a8eVyBvzF0YyGJJ0IWmQ==,iv:kHTqHtFJm9ErmaknBsys+eRXoKfY3uiKpq++lX9P+bU=,tag:Aj7JGsTjR1puuhVQadQIBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcmFBY09iRGRWQlpIWW11
            alZ0Q0xuZmtDVFhoNDZsMXZTbUk1R1JIL1VJCmRhRnphdmw0bko4VURCZlNGWVRo
            ZmZlNjA3MmRuY2g5Qy9PNHJYbk4wNlEKLS0tIEh2YjVUKzk0T1FrWmdRbU1kckhD
            Mzk1NWtkMk13N1pEUkQyMVZWbDg5emMKCueQB3bM/IEXXJET3CwtBmk7auiVChGo
            PTCd0it6iPelVESL0XcWuLJnlRK8rpRy569f19EMGPypRgOTRDMsTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
    lastmodified: "2026-06-13T09:37:03Z"
    mac: ENC[AES256_GCM,data:VogCO2eGxBc/sDtLLsYYMSCP35/KG6r42LosPfPbogKnNByhsRV1JrUSG9TRp8Cp71L8FY8SV10QCUyHgy4tUWW4GsWuv/pENogurKDOBvjElB5EKEB3n4sO4TaST0hLtDJSCw8X1iV9gmWO2h+gM4vy4VOffrzRBcHUaY4raJI=,iv:+sCS3aotYxUqq3HYltR+VMEea2xnjMWcApI18RmDkvU=,tag:3APD52XNslmwDrECT8ya8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
