---
- name: reload systemd daemon
  systemd_service:
    daemon_reload: true

- name: restart kubelet
  systemd_service:
    name: kubelet
    state: restarted

- name: restart containerd
  systemd_service:
    name: containerd
    state: restarted
