---
- name: configure kubelet IPs
  copy:
    dest: /etc/default/kubelet
    content: |
      Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }},{{ node_ula_prefix }}{{ node_suffix }}"
  notify:
    - reload systemd daemon
    - restart kubelet

- meta: flush_handlers
