---
- name: enable IPv4 and IPv6 packet forwarding
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_set: true
  with_items:
    - name: net.ipv4.ip_forward
      value: "1"
    - name: net.ipv6.conf.all.forwarding
      value: "1"
    - name: net.ipv6.conf.all.accept_ra
      value: "2"

- name: get node suffix from IPv4 address
  set_fact:
    node_suffix: "{{ ansible_default_ipv4.address.split('.')[-1] }}"

# not all of the cloud-init configs get written to disk (possibly due to old netplan in the netinstall image?)
- name: configure k8s IPv4
  copy:
    src: 50-cloud-init.yaml
    dest: /etc/netplan/50-cloud-init.yaml
    mode: "0640"
  register: netplan_config

- name: apply netplan configuration
  command: netplan apply
  when: netplan_config.changed
  changed_when: true

- name: configure k8s IPv6 ULA subnet
  template:
    src: 60-k8s-ipv6.yaml.j2
    dest: /etc/netplan/60-k8s-ipv6.yaml
    mode: "0640"
  register: netplan_config

- name: apply netplan configuration
  command: netplan apply
  when: netplan_config.changed
  changed_when: true
