---
- name: restart unattended-upgrades
  systemd_service:
    state: restarted
    name: unattended-upgrades

- name: update grub
  command: update-grub
  changed_when: true

- name: reboot
  reboot:
