sops_age_key: ENC[AES256_GCM,data:ktMr8QHrceqYOsNwklgzgKKu/k/PcqbFxMiYy0MeaGsPlYTLEl8N4qQ1Hq6HQmYaujbF+C6oHSGGEUlA4RHE+BOSU0Xqvqgm/8Y=,iv:958/evDmOwTI0IVKSrCVBktRb9JeAC8MPQUgOH0td4s=,tag:DoXCDhvqdaIASpY45FK06A==,type:str]
sops:
    age:
        - recipient: age168avplsha0pc878zkkgnx2n7zku0grgmwal2grmxjxnx579j9ffq0a0yfp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ29BcFMvYVlSRDAvM0Z5
            L1ovS0F0bDA0WWRrU01wTEJobThXSlRaZzJRCmQ0RElnOWh5cGhacUt0RUM4c3Nn
            cVA2cTlwRkFOdk80ajRTSkFOMElNNHcKLS0tIFRoVVpsTmpBcUtxRFp2S01KK1pT
            TTQxK1hxN2dtNHFtSjdjWEd0RWw0cG8KBJ42HVoRq+q9AmIZduHRjARikbzgPCQg
            xeBHejEsiZd5nKlu/C5ASNrhmKNwnHZjMgsbZjvbwrDqX+nHV2+kjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-18T18:39:05Z"
    mac: ENC[AES256_GCM,data:ofaroP40Q9xs0VyhSJvnMeYPfGUk/Q1dfH4JMfryNjMUpp2oL4GjTpz9iJZd2o2TaX+IvonFWh+UMgzl8HvEBG4L+GRdt9jIvr++3fspV1peOP//P4LAVPRvkEbnvrP4FuO6Z2KNnaTEt9gtxX2QERmanP0PKSKsR+XTAxnFE6A=,iv:GLMoWnMVt4YqCywRVlFnG0hXV85AwD9r3VvcqLc3wPU=,tag:bI4I+99+/CxYbFLp1r18wg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
