apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1m
  chart:
    spec:
      chart: authentik
      version: 2026.5.6
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  values:
    authentik:
      existingSecret:
        secretName: authentik-secrets
      error_reporting:
        enabled: false
    server:
      ingress:
        enabled: false
    postgresql:
      enabled: false
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      encoding: UTF8
      localeCollate: C
      localeCType: C
      secret:
        name: authentik-postgres-user
  storage:
    size: 10Gi
    storageClass: cluster-scratch
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-gateway
  namespace: authentik
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: authentik
    hostname: authentik.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: authentik-server
        port: 80
    redirect:
      enabled: false
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik
  namespace: authentik
spec:
  endpoints:
  - dnsName: authentik.${SERVICE_DOMAIN}
    recordType: A
    targets:
    - 192.168.1.6
