apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks-system
spec:
  interval: 1m
  chart:
    spec:
      chart: goldilocks
      version: 10.4.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.15.1@sha256:244b52b53aa4bb56b53c50f5b6b617612619a8f76571bd1e21d7d8157b3aee9e
    controller:
      rbac:
        enableArgoproj: false
      flags:
        on-by-default: true
    dashboard:
      flags:
        on-by-default: true
      ingress:
        enabled: false
      httpRoute:
        enabled: true
        parentRefs:
          - group: gateway.networking.k8s.io
            kind: ListenerSet
            name: goldilocks
            namespace: goldilocks-system
            sectionName: https
        hostnames:
          - goldilocks.${SERVICE_DOMAIN}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: goldilocks-tls
  namespace: envoy-gateway-system
spec:
  secretName: goldilocks-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  dnsNames:
    - goldilocks.${SERVICE_DOMAIN}
---
apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: goldilocks
  namespace: goldilocks-system
spec:
  parentRef:
    name: shared
    namespace: envoy-gateway-system
  listeners:
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "goldilocks.${SERVICE_DOMAIN}"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: goldilocks-tls
            namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: goldilocks-listenerset-to-goldilocks-tls
  namespace: envoy-gateway-system
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      namespace: goldilocks-system
  to:
    - group: ""
      kind: Secret
      name: goldilocks-tls
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: goldilocks-http-redirect
  namespace: goldilocks-system
spec:
  parentRefs:
    - name: shared
      namespace: envoy-gateway-system
      sectionName: http
  hostnames:
    - "goldilocks.${SERVICE_DOMAIN}"
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
