apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: goldilocks-system
spec:
  interval: 1m
  chart:
    spec:
      chart: goldilocks
      version: 10.1.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.14.6@sha256:2ad3599ba03c2736a699befd2ea15f087c27626e96eb7db957a632b4abb44a3a
    controller:
      rbac:
        enableArgoproj: false
      flags:
        on-by-default: true
    dashboard:
      flags:
        on-by-default: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - host: goldilocks.${SERVICE_DOMAIN}
            paths:
              - path: /
                type: Prefix
        tls:
          - secretName: goldilocks-tls
            hosts:
              - goldilocks.${SERVICE_DOMAIN}
