apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: 10.5.15
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      storageClassName: cluster-scratch
      size: 1Gi
    admin:
      existingSecret: grafana-secrets
      userKey: admin-user
      passwordKey: admin-password
    grafana.ini:
      server:
        domain: grafana.${SERVICE_DOMAIN}
        root_url: https://grafana.${SERVICE_DOMAIN}
    sidecar:
      alerts:
        enabled: true
        label: grafana_alert
        labelValue: "1"
      dashboards:
        enabled: true
        searchNamespace: ALL
        label: grafana_dashboard
        labelValue: "1"
        folderAnnotation: grafana_dashboard_folder
        provider:
          foldersFromFilesStructure: true
      datasources:
        enabled: true
        searchNamespace: ALL
        label: grafana_datasource
        labelValue: "1"
      plugins:
        enabled: true
        label: grafana_plugin
        labelValue: "1"
      notifiers:
        enabled: true
        label: grafana_notifier
        labelValue: "1"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-gateway
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: grafana
    hostname: grafana.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: grafana
        port: 80
