apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 87.17.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    crds:
      upgradeJob:
        enabled: true
    alertmanager:
      ingress:
        enabled: false
      alertmanagerSpec:
        retention: 168h
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: cluster-scratch
              resources:
                requests:
                  storage: 1Gi
    grafana:
      enabled: false
      forceDeployDatasources: true
      forceDeployDashboards: true
      defaultDashboardsEnabled: true
      defaultDashboardsTimezone: Europe/Berlin
      defaultDashboardsEditable: true
      sidecar:
        dashboards:
          annotations:
            grafana_dashboard_folder: kube-prometheus-stack
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        retention: 90d
        retentionSize: 250GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: nas-replicated-hdd
              resources:
                requests:
                  storage: 250Gi
        podMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alertmanager-gateway
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: alertmanager
    hostname: alertmanager.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: kube-prometheus-stack-alertmanager
        port: 9093
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-gateway
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: prometheus
    hostname: prometheus.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: kube-prometheus-stack-prometheus
        port: 9090
