apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-healthcheck-to-cronjobs
spec:
  failurePolicy: Fail
  rules:
    - name: make-containers-into-init-containers
      match:
        resources:
          kinds:
            - batch/v1/CronJob
      preconditions:
        all:
          - key: "{{ request.object.metadata.annotations.healthcheckSecret || '' }}"
            operator: NotEquals
            value: ""
      mutate:
        foreach:
          - list: request.object.spec.jobTemplate.spec.template.spec.containers
            preconditions:
              all:
                - key: "{{ element.name }}"
                  operator: NotEquals
                  value: "healthcheck"
            patchStrategicMerge:
              spec:
                jobTemplate:
                  spec:
                    template:
                      spec:
                        initContainers:
                          - "{{ element }}"
    - name: replace-containers-with-healthcheck
      match:
        resources:
          kinds:
            - batch/v1/CronJob
      preconditions:
        all:
          - key: "{{ request.object.metadata.annotations.healthcheckSecret || '' }}"
            operator: NotEquals
            value: ""
      mutate:
        # have to rely on ASCII escape (\x24) for the shell evaluation
        # - $(VAR) would cause substitution/failure by kyverno
        # - ${VAR} would cause substitution/failure by flux
        # - \$(VAR) would cause parsing failure ("found unknown escape character")
        # - $VAR does not actually evaluate in this case
        patchesJson6902: |-
          - path: "/spec/jobTemplate/spec/template/spec/containers"
            op: replace
            value:
              - name: healthcheck
                image: ghcr.io/anokfireball/base-image:3.24.1@sha256:e944a2132ca4c0a0bb3e37d65cb96958a2e8e6d1f4b1784770efbd3f3b8c1258
                command: ["bash", "-c"]
                args:
                  - "set -euo pipefail;
                     start=\"\x24(stat -c %Y /rt)\";
                     runtime=\x24(( \x24(date +%s) - start ));
                     url=\"\x24(HEALTHCHECK)\";
                     sep=\"?\";
                     if [[ \"\x24url\" == *\"?\"* ]]; then sep=\"&\"; fi;
                     curl -fs --globoff -X POST \"\x24{url}\x24{sep}duration=\x24{runtime}s\" -H \"Authorization: Bearer \x24(TOKEN)\""
                volumeMounts:
                  - name: healthcheck-runtime
                    mountPath: /rt
                env:
                  - name: HEALTHCHECK
                    valueFrom:
                      secretKeyRef:
                        name: "{{ request.object.metadata.annotations.healthcheckSecret }}"
                        key: healthcheckUrl
                  - name: TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: "{{ request.object.metadata.annotations.healthcheckSecret }}"
                        key: healthcheckToken

    - name: add-runtime-volume
      match:
        resources:
          kinds:
            - batch/v1/CronJob
      preconditions:
        all:
          - key: "{{ request.object.metadata.annotations.healthcheckSecret || '' }}"
            operator: NotEquals
            value: ""
      mutate:
        patchStrategicMerge:
          spec:
            jobTemplate:
              spec:
                template:
                  spec:
                    volumes:
                      - name: healthcheck-runtime
                        emptyDir: {}
