apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-gateway
  namespace: longhorn-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/gateway-route
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    name: longhorn
    hostname: longhorn.${SERVICE_DOMAIN}
    route:
      enabled: true
      backend:
        name: longhorn-frontend
        port: 80
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cluster-scratch
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  numberOfReplicas: "1"
  dataLocality: best-effort
  recurringJobSelector: |
    [
       {
         "name":"base",
         "isGroup":true
       }
     ]
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cluster-replicated
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "3"
  dataLocality: best-effort
  replicaAutoBalance: best-effort
  recurringJobSelector: |
    [
       {
         "name":"base",
         "isGroup":true
       },
       {
         "name":"daily-backup",
         "isGroup":false
       }
     ]
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  cron: 45 23 * * *
  name: daily-backup
  retain: 7
  task: backup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-snapshot-cleanup
  namespace: longhorn-system
spec:
  cron: 30 23 * * *
  groups:
    - base
  name: daily-snapshot-cleanup
  task: snapshot-cleanup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-trim
  namespace: longhorn-system
spec:
  cron: 0 0 * * 0
  groups:
    - base
  name: weekly-trim
  task: filesystem-trim
