apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring-system
spec:
  interval: 1m
  chart:
    spec:
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    config:
      clients:
        - url: http://loki.monitoring-system:3100/loki/api/v1/push
          headers:
            X-Scope-OrgID: "1"
    sidecar:
      configReloader:
        enabled: true
