apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: csi-snapshotter
  path: ./client/config/crd/
