---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns-vip
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.3/32
    - fd08:192:168:1::3/128
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: http-vip
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.4/32
    - fd08:192:168:1::4/128
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-vip
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.5/32
    - fd08:192:168:1::5/128
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - dns-vip
    - http-vip
    - default-vip
  interfaces:
    - eth0
